### ISSUE TITLE
Fetch type default option 

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#136]
Hi!

Could possibly JPA modeler contain option to make all unspecified Fetch Type make LAZY by default, 
like it is done with Optional Return Type ?

E.g. if 
Default fetch type is unspecified, then no changes is made to code generation
if Default fetch type = LAZY, then all relationships (OneToOne, ManyToOne, OneToMany, ManyToMany) with unspecified fetch type  generated witch fetch type=LAZY
and so with EAGER (altough i am need only LAZY by default)

**Comment by slavb18** [comment]
From the JPA 2.0 spec, the defaults are like so:
OneToMany: LAZY
ManyToOne: EAGER
ManyToMany: LAZY
OneToOne: EAGER

*ToOne fetch set to EAGER is legacy from JPA 1.0  
Currently all JPA  providers support LAZY associations (or  will simply ignore LAZY in case to Java EE environment or no weaving in Java SE occurs

So making default LAZY makes sense

**Comment by jGauravGupta** [comment]
Alternate enhancement ref :  https://github.com/jeddict/jeddict/issues/172

**Comment by jGauravGupta** [comment]
This functionality will be available only for OneToOne and ManyToOne.
