### ISSUE TITLE
Error in generated WEB-INF/web.xml

### ISSUE THREAD

**Issue by pembertonc** [jeddict/jeddict#167]
I am using Netbeans 8.2 and jpaModeler / jeddict 3.6

The following is generated as the web.xml 

 <data-source>
        <name>java:global/jdbc/java:app/jdbc/naits</name>
        <class-name>org.postgresql.xa.PGXADataSource</class-name>
        <server-name>${db.host}</server-name>
        <port-number>${db.port}</port-number>
        <database-name>${db.name}</database-name>
        <user>${db.user}</user>
        <password>${db.password}</password>
    </data-source>

running Validate against it results in:
XML validation started.
Checking file:/C:/Users/cedri/Documents/NetBeansProjects/SVG-NAITS-BACKEND/src/main/webapp/WEB-INF/web.xml...
cvc-datatype-valid.1.2.1: '${db.port}' is not a valid value for 'integer'. [10] 
cvc-complex-type.2.2: Element 'port-number' must have no element [children], and the value must be valid. [10] 
XML validation finished.

To Fix I replace ${db.port} with the actual port number.

Respectfully

Cedric Pemberton

**Comment by jGauravGupta** [comment]
These value are replaced by dev profile properties 
```
        <profile>
            <id>dev</id>
            <activation>
                <property>
                    <name>!prod</name>
                </property>
            </activation>
            <properties>
                <db.password>secret</db.password>
                <db.user>myuser</db.user>
                <db.port>3306</db.port>
                <db.name>sample</db.name>
                <db.host>db</db.host>
            </properties>
        </profile>
```
using following plugin 

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <webResources>
                        <resource>
                            <filtering>true</filtering>
                            <directory>src/main/webapp</directory>
                            <includes>
                                <include>**/web.xml</include>
                            </includes>
                        </resource>
                    </webResources>
                    <warSourceDirectory>src/main/webapp</warSourceDirectory>
                    <webXml>src/main/webapp/WEB-INF/web.xml</webXml>
                </configuration>
            </plugin>
```

**Comment by pembertonc** [comment]
Greetings,
Yes both the plug in and the profile are present in pom.xml.   Netbeans 8.2 complains about the malformed XML and validation fails.  However the project compiles and runs.

Thanks

**Comment by jGauravGupta** [comment]
This is the one of the vendor independent way of data-source registration using web.xml.
