### ISSUE TITLE
Allow to choose explicitly the Fetch Type like eager or lazy

### ISSUE THREAD

**Issue by samyomar** [jeddict/jeddict#171]
in DB reverse engineering dialog , we need an option to use Fetch Type  strategy like eager or lazy

**Comment by jGauravGupta** [comment]
Hi @samyomar ,
reverse engineering dialog means here Database reverse engineering ?

**Comment by samyomar** [comment]
Yes.

**Comment by jGauravGupta** [comment]
This ticket has been closed as this functionality depends on NetBeans API so can not be implemented here.
