### ISSUE TITLE
in jpa modeler designer, general attributes configuration is required that apply to all JPA entities

### ISSUE THREAD

**Issue by samyomar** [jeddict/jeddict#172]
in the jpa modeler designer, we need a general attribute to set for all JPA entities at once.
like use EAGER cache strategy .  this feature is currently found on every jpa entity list field.

So to change this on the whole project it will take a lot of time.

**Comment by slavb18** [comment]
I agree, such default settings should be saved per-model file

**Comment by jGauravGupta** [comment]
Refer this [https://github.com/jeddict/jeddict/issues/136] issue for further discussion.
