### ISSUE TITLE
Add feature to look for Entity in diagram

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#186]
For big models is sometimes hard to find the entity you need. It would be nice to have some kind of either search field that then finds and shows the entity in as center of the view or having a side panel with a list of the entities that you could modify from there for example.

Here's an example of such big model.

![jpa_model jpa](https://cloud.githubusercontent.com/assets/2817343/24461920/48aa6f1a-1468-11e7-8408-2ccb7ca432ff.png)

**Comment by slavb18** [comment]
Just wanted to write such proposal
