### ISSUE TITLE
Error vizualizing Database (Version 4.0.0)

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#187]
See attached error as it didn't fit in the field.

[Error Output.txt](https://github.com/jeddict/jeddict/files/880480/Error.Output.txt)

**Comment by javydreamercsw** [comment]
Here's the diagram export.
![jpa_model jpa](https://cloud.githubusercontent.com/assets/2817343/24478421/5cd40b9e-14a0-11e7-9764-01a983acd181.png)

**Comment by jGauravGupta** [comment]
Hi @javydreamercsw ,
This is already fixed in master branch. Release will be avialable soon. 
Issue is with RequirementSpecNode entity have self relation with composite pk.

I will suggest you to use workspace and exclude this entity at the moment.
