### ISSUE TITLE
Error: New release v4.1 does not display model

### ISSUE THREAD

**Issue by vitavitall** [jeddict/jeddict#189]
![screen_res](https://cloud.githubusercontent.com/assets/17187877/24536672/fd2f79d2-15ec-11e7-88b0-54db611a457b.png)

If you need I can send the model to the mail.

**Comment by jGauravGupta** [comment]
Hi @vitavitall ,

Please share here : gaurav.gupta.jc@gmail.com

**Comment by jGauravGupta** [comment]
Is it also not working for newly created modeler file ?

**Comment by vitavitall** [comment]
Does not work for some old files only.
Sent.

**Comment by vitavitall** [comment]
Thank you.
Need to remove from model.jpa:
`m="true"`
