### ISSUE TITLE
Feature to allow automatic history entity/table creation

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#190]
Hi!

EclipseLink provides support for history tables, however, it lacks support for auto history table creation.
https://wiki.eclipse.org/EclipseLink/Examples/JPA/History

Automatic table creation and extending could be achieved by special "History Entity"
e.g.

Base entity

```java
@Entity
public class Person {

   @Id
   private Long personId;
   private String firstName;
   private String lastName;
   ..
} 
```

History entity contains same fields, except @Id field (personId in example) should be @Basic, becouse it will contain many records with same id

And additionally it should contain fields (could be modelled as usual)

```java
@Entity
public class PersonHist {

   @Id
   private Long histId;

   // Add here the extra fields/columns that should exist for the
   // history table.
   private Date rowStartTime;
   private Date rowEndTime;
   ..
}
```

My proposal is to create "mirror", or "history" entity, based on real entity, which will replicate all fields from the base entity,
except replacing @Id with @Basic (or allows attribute override)
And allows to specify additional fields, like 
@Id private Long histId;
 private Date rowStartTime;
 private Date rowEndTime;

Base idea is to allow modeling special "mirror" entities, with possibility to add / override fields from base entity

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,

So What you want to achieve finally , please have a look on following points: 

- Generate HistoryCustomizer  class https://wiki.eclipse.org/EclipseLink/Examples/JPA/History
- Quick cloning of existing entity
- Generate History table SQL in DB Modeler
- Visualization of history table in JPA and DB modeler

**Comment by slavb18** [comment]
I want to have Entity, which will  replicate all fields from the base entity.
E.g. when I add  new property to base entity, it will be virtually added to mirror entity,
And I can add and override fields ,e.g make @Id field @Basic one.

But this is not inheritance, this is independent entity.

All other work (create, extend tables) will be done through persistance provider as regular entity.

**Comment by jGauravGupta** [comment]
And source code generation time will it also generate ${Entity}History.java ?

**Comment by slavb18** [comment]
1) at creation time, mirror entity is same  as base entity, it extends same class, contains same fields
2) i can add fields to it, like 
   @Id
   private Long histId;
   private Date rowStartTime;
   private Date rowEndTime;

3) i can override fields, like make
 @Basic
   private Long personId;
istead of @Id
4) By default, relationship enforces foreign key creation, sometimes this is not not convenient, to have history foreign check, when i want to remove dependend object

 I can override relationships, e.g. disable foreign key constrait creation 
foreignKey=@ForeignKey(value=ConstraintMode.NO_CONSTRAINT)



As you see, lot of excludes :), and you may find this not worth implementing.
However, this can benefit in case of complex entities with many -many fields.


There is also feature request to eclipselink 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=330397
But generation is of real entity is much better, becouse all properies are real 
E.g. there is no real properies
```
@Entity
@HistoryTable(base=Person.class, primaryKeyFields="personId,rowStartTime")
public class PersonHist {

   // Add here the extra fields/columns that should exist for the
   // history table.
   private Date rowStartTime;
   private Date rowEndTime;
   ..
}
```

**Comment by slavb18** [comment]
Another possible solution , and much simpler, is to allow one-moment entity copy - and paste. And property copy-and paste.

**Comment by jGauravGupta** [comment]
```@HistoryTable(base=Person.class, primaryKeyFields="personId,rowStartTime")```
Not much sure but with @HistoryTable solution  will more proprietor solution.

**Copy and paste** will be the base functionality of modeler.

**Comment by slavb18** [comment]
No, I am not voting for @HistoryTable solution
I am just looking way to simplify history entity creation without manually duplication of entire model

**Comment by jGauravGupta** [comment]
To manage cloned will also not be easy , if they are not internally connected.

Right what approach , you are using can you share the sample code.
As per this link (https://wiki.eclipse.org/EclipseLink/Examples/JPA/History) no duplicate entity is created.

**Comment by slavb18** [comment]
History Entity is not required for history to work, only tables required.
But if we require to display entity history, then entity is handy
And also with Entity  i have automatic history table  creation and extending (automatic adding new fields)

I will make history support in my test project and share the link.

Another option is to introduce mapped super class without @Id, and then make Entity and EntityHist by real inheritance, but looks like there is no option to disable FK constrait generation in derived class.

And to make mapped super class is also lot of hand work.

**Comment by slavb18** [comment]
https://github.com/ilb/jparestresource
with manual table creation
https://github.com/ilb/jparestresource/blob/master/src/main/resources/META-INF/sql/create.sql

if you ever can find time to run my project, there is some configuration required
1) select "standalone" profile in maven, to package eclipselink in war
OR
2) place jars in tomcat https://github.com/ilb/jparestresource#environment-configuration

**Comment by slavb18** [comment]
Added History entities

https://github.com/ilb/jparestresource/blob/master/src/main/java/ru/ilb/jparestresource/model/DocfileHist.java
https://github.com/ilb/jparestresource/blob/master/src/main/java/ru/ilb/jparestresource/model/DocumentHist.java

Diffrerences from  base entitiies

added
```java
    @Column(nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long histId;
    
    @Basic
    private LocalDateTime rowStart;

    @Basic
private LocalDateTime rowEnd;
```

replaced
```java
    @Basic
private Long id;
```

removed @OneToMany
```java
    @XmlTransient
    @OneToMany(targetEntity = Docfile.class,mappedBy = "document")
private List<Docfile> docfiles;
```

configured no constrait on ManyToOne
```java
    @JoinColumn(name="DOCUMENT_ID",referencedColumnName="ID",nullable=false,foreignKey=@ForeignKey(value=ConstraintMode.NO_CONSTRAINT))
    private Document document;

```

So history entity is same as base entity, with 
1) 3 fields added: histId, rowStart, rowEnd
2) original @Id removed
3) only contains @Basic and "owned" fields (@ManyToOne and @OneToOne) with no foreign key check


Can I "script" such entity generation, without even touching model?

**Comment by jGauravGupta** [comment]
Not possible currently ? 
But possible solution could be , just design history entity as usual and common(unchanged) attribute can be imported from other entity and these imported will not be visible on screen , will be part of only source code generation.

**Comment by slavb18** [comment]
May be "mirrored" entity could contain all base entify fields "grayed"
And modeler allow to add, remove and override fields.
E.g. I can add fields, delete fields, like OneToMany mapping, override ManyToOne and OneToOne mapping (disable constrait if required),
override @Id field

Generated source will extend same class as base entity, contain all "grayed" fields (inherited from base entity) and newly added and overridden fields, except deleted fields.

**Comment by slavb18** [comment]
Just found, @AssociationOverride allows to override foreignKey!
So another option is to make some functionality to extract Super Class from entity, like Netbeans  Refactor-> Extract supreclass.
User checks fields, and jeddict create mapped superclass with checked fileds, and make target class extend mapped superclass.
I can check all @Basic and @ManyToOne fields to move them to mapped super class.

Then I can extend mapped superclass with History Entity, add histId, rowStart and rowEnd
and override ManyToOne foreign key constrait.

Or, more simple solution, when just copy and paste appears, i can copy fields to mapped superclass and delete then in source entity

**Comment by slavb18** [comment]
Also someday jeddict could have interface to manage @AssociationOverrides on entity

**Comment by slavb18** [comment]
example model
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="ru.ilb.jparestresource.model" v="3.1" rws="_14881688460591" Pws="_14881688460591" cws="_14881688460591" persistenceUnitName="jparestresource" sm="false" xs="true" id="_14855761330684" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:description>jparestresource model</jpa:description>
    <jpa:mapped-superclass xre="false" compositePrimaryKeyClass="DocumentBasePK" abs="false" class="DocumentBase" v="true" m="false" rootElement="_14855761330684" id="_1491468474874">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>slavb</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="displayName" id="_14914684884581750">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" name="description" id="_14914684950581751">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="java.time.LocalDate" v="true" name="docDate" id="_14914684995301752">
                <jpa:bv/>
            </jpa:basic>
        </jpa:attributes>
        <jpa:nq e="false" name="DocumentBase.findAll">
            <jpa:query>Select m from DocumentBase m</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocumentBase.findByDisplayName">
            <jpa:query>Select d from DocumentBase d where d.displayName=:displayName</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocumentBase.findByDescription">
            <jpa:query>Select d from DocumentBase d where d.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocumentBase.findByDocDate">
            <jpa:query>Select d from DocumentBase d where d.docDate=:docDate</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:mapped-superclass>
    <jpa:mapped-superclass xre="false" compositePrimaryKeyClass="DocfileBasePK" abs="false" class="DocfileBase" v="true" m="false" rootElement="_14855761330684" id="_1491468627682">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>slavb</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="Boolean" v="true" name="confirm" id="_14914686403681759">
                <jpa:des>Confirmation status</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" name="userName" id="_14914686663041760">
                <jpa:des>User created</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" v="true" name="comment" id="_14914688013181761">
                <jpa:des>File comment</jpa:des>
                <jpa:bv/>
            </jpa:basic>
        </jpa:attributes>
        <jpa:nq e="false" name="DocfileBase.findAll">
            <jpa:query>Select m from DocfileBase m</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileBase.findByComment">
            <jpa:query>Select d from DocfileBase d where d.comment=:comment</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileBase.findByConfirm">
            <jpa:query>Select d from DocfileBase d where d.confirm=:confirm</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileBase.findByUserName">
            <jpa:query>Select d from DocfileBase d where d.userName=:userName</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileBase.findByComment">
            <jpa:query>Select d from DocfileBase d where d.comment=:comment</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:mapped-superclass>
    <jpa:entity xre="true" compositePrimaryKeyClass="DocfilePK" abs="false" class="Docfile" superclassId="_1491468627682" v="true" m="false" rootElement="_14855761330684" id="_14855761330685">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:annotation e="true" n="@org.eclipse.persistence.annotations.Customizer(ru.ilb.jparestresource.persistance.HistoryCustomizer.class)"/>
        <jpa:attributes>
            <jpa:many-to-one optional="true" primaryKey="false" connected-entity-id="_14855761330696" connected-attribute-id="_148557613307823" v="true" xvt="I_E" name="document" id="_148557613307714">
                <jpa:bv/>
                <jpa:join-column name="DOCUMENT_ID" rc="ID" unique="false" nullable="false" insertable="true" updatable="true" column-definition="" table=""/>
            </jpa:many-to-one>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14855761330767">
                <jpa:bv/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="true" compositePrimaryKeyClass="DocumentPK" abs="false" class="Document" superclassId="_1491468474874" v="true" m="false" rootElement="_14855761330684" id="_14855761330696">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:annotation e="true" n="@org.eclipse.persistence.annotations.Customizer(ru.ilb.jparestresource.persistance.HistoryCustomizer.class)"/>
        <jpa:attributes>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_14855761330685" connected-attribute-id="_148557613307714" v="true" xvt="E" name="docfiles" id="_148557613307823">
                <jpa:xe nillable="false" required="false"/>
                <jpa:bv/>
                <jpa:cascade>
                    <jpa:cascade-all/>
                </jpa:cascade>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14914685534661755">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="DocumentHistPK" abs="false" class="DocumentHist" superclassId="_1491468474874" v="true" m="false" rootElement="_14855761330684" id="_1491468539018">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>slavb</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="Long" v="true" name="id" id="_14914685926891756">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="java.time.LocalDateTime" v="true" name="rowStart" id="_14914688623571764">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="java.time.LocalDateTime" v="true" name="rowEnd" id="_14914688654541765">
                <jpa:bv/>
            </jpa:basic>
            <jpa:id attribute-type="Long" v="true" name="histId" id="_14914685390181753">
                <jpa:bv/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="DocumentHist.findAll">
            <jpa:query>Select e from DocumentHist e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocumentHist.findById">
            <jpa:query>Select d from DocumentHist d where d.id=:id</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocumentHist.findByRowStart">
            <jpa:query>Select d from DocumentHist d where d.rowStart=:rowStart</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocumentHist.findByRowEnd">
            <jpa:query>Select d from DocumentHist d where d.rowEnd=:rowEnd</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity lbl-ref="_14914686403681759" xre="false" compositePrimaryKeyClass="DocfileHistPK" abs="false" class="DocfileHist" superclassId="_1491468627682" v="true" m="false" rootElement="_14855761330684" id="_1491468837419">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>slavb</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="java.time.LocalDateTime" v="true" name="rowStart" id="_14914689377891766">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="java.time.LocalDateTime" v="true" name="rowEnd" id="_14914689428131767">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="Long" v="true" name="id" id="_14914699061281809">
                <jpa:bv/>
            </jpa:basic>
            <jpa:many-to-one optional="true" primaryKey="false" connected-entity-id="_14855761330696" v="true" name="document" id="_14914689999081768">
                <jpa:bv/>
                <jpa:join-column name="DOCUMENT_ID" unique="false" nullable="true" insertable="true" updatable="true">
                    <jpa:fk constraint-mode="NO_CONSTRAINT"/>
                </jpa:join-column>
            </jpa:many-to-one>
            <jpa:id attribute-type="Long" v="true" name="histId" id="_14914688374191762">
                <jpa:bv/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="DocfileHist.findAll">
            <jpa:query>Select e from DocfileHist e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileHist.findByRowStart">
            <jpa:query>Select d from DocfileHist d where d.rowStart=:rowStart</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileHist.findByRowEnd">
            <jpa:query>Select d from DocfileHist d where d.rowEnd=:rowEnd</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="DocfileHist.findById">
            <jpa:query>Select d from DocfileHist d where d.id=:id</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:inf e="true" n="java.io.Serializable"/>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14881688460591">
            <i ref="_1491468627682" x="555" y="169"/>
            <i ref="_1491468474874" x="145" y="152"/>
            <i ref="_1491468837419" x="557" y="325"/>
            <i ref="_1491468539018" x="147" y="305"/>
            <i ref="_14855761330685" x="568" y="8"/>
            <i ref="_14855761330696" x="158" y="8"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```
![model jpa](https://cloud.githubusercontent.com/assets/2534896/24746751/4a6819c4-1acb-11e7-89db-14068b5604ca.png)

**Comment by slavb18** [comment]
I was unable to add ManyToOne to mapped superclass in jeddict, however JPA allows this.
I simply duplicated it in Docfile and DocfileHist

**Comment by slavb18** [comment]
So, I can model History entity in Jeddict without property duplication (except for ManyToOne, becouse i cannot add ManyToOne to mapped superclass, I can file separate issue)

I simply cannot currently refactor my current (complex) model using some sort of refactor ("extract superclass")  or copy and paste.

Also I cam file seperate issue about extract superclass, if you see this promising.

**Comment by jGauravGupta** [comment]
mapped superclass only supports uni-directional relationship as per spec.

**Comment by slavb18** [comment]
Understand, so only basic fields could be shared between Entity and History.

**Comment by slavb18** [comment]
Any chance copy and paste property functionality will appear in near future?

**Comment by jGauravGupta** [comment]
Yes it will be available in future but recently I changed the job so for next few months fix will be available only for blocker issue.

**Comment by slavb18** [comment]
Thanks for your attention, then I close this issue
