### ISSUE TITLE
Select from existing Persistance units when creating from existing entities

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#194]
Right now it creates a PU by default. That's fine as long as there are none defined. It should be able to read the persistence file and let you select to use one of the existent or create the default.

**Comment by jGauravGupta** [comment]
To select the existing PU, You can change the persistence unit name here  : 
**Diagram > Properties > Basic Properties > Persistence Unit Name**

**Comment by javydreamercsw** [comment]
I know how to select the PU, but the wizard doesn't allow this ending always with a Default persistence unit added when they are existing ones already.

**Comment by jGauravGupta** [comment]
By default PersistenceUnit name is "DEFAULT_PU" in JPA Diagram as shown in following diagram : 
![1](https://cloud.githubusercontent.com/assets/15934072/24878738/f6de140e-1e51-11e7-8870-58a9a11a2e8c.PNG)

Just change this value with your existing PersistenceUnit name then it will not create the new PersistenceUnit and reuse the existing one configured by you
![2](https://cloud.githubusercontent.com/assets/15934072/24878739/f6e31102-1e51-11e7-8c6d-4f9f7804c500.PNG)

**Comment by javydreamercsw** [comment]
It is. What I mean is that the wizard should be able to detect existing persistence units and prompt to use an existing one or create the default one. That was the purpose of the enhancement request.
