### ISSUE TITLE
Import existing beans into a existing diagram 

### ISSUE THREAD

**Issue by chrisknoll** [jeddict/jeddict#195]
I'm not sure if I am missing it in the UI or if this is not something that's supported, but I've started a new diagram (to get familiar with the jeddict tool) and it's working very well, so I'd like to make some references from the new entities I created in the jeddict JPA diagram to existing entities that's in the codebase.  I can't find a way to import existing entities into the current diagram.  Is this possible, or is this a new feature request?

Additional request:  I'm guessing that the import of the entity might not be exactly what it was in the source code, but if I generate source from the diagram, all the classes are overwritten.  Is there a way to mark one of the entities in the diagram to not generate, or is it 'all or nothing'?

-Chris

**Comment by jGauravGupta** [comment]
Hi @chrisknoll ,

- If you want to import existing entities from code base : New File > Persistence > JPA Diagram from Reverse Engineering (Classes)

- If you want to import existing entities from code base in existing modeler then it is not supported : New feature request ref : https://github.com/jeddict/jeddict/issues/133

- Classes Reverse Engineering is not supported for constructor/hashcode/equals/toString/custom_method etc.

- For Selected entity generation, click the icon as shown in following image : 
![selectcode](https://cloud.githubusercontent.com/assets/15934072/24876260/a81210c2-1e48-11e7-96ba-af5096c72a01.png)

**Comment by chrisknoll** [comment]
Thank you, @jGauravGupta , bullet two (ref #133) is what I was asking about.  Look forward to that feature! (it doesn't even have to be drag-drop, btw, if it was just a matter of opening the file and parsing it in, that would be good.  And being able to drag entities between JPA diagrams would also solve this problem (giving you the use case where you are playing around with a temporary jpa diagram and once finalized, drag a group of entities from one diagram to another diagram).

That option you gave for selected generation will work, but my worry is someone accidentally forgetting to not de-select one of the entities for generation, which is why a flag within the diagram that you could set (exclude entity option in the property of the entity) would prevent that mistake.

The reason for this case is that there may be custom Entity code (such as the hashcode or equals() implementation, or even other bean customization (like adding toDTO methods to it) or any other custom addition to the bean that you do _not_ want overwritten by the JPA modeler), but you still want to reference it in the jpa diagram to set up references between beans.

-Chris

**Comment by Manoj-Madushantha** [comment]
Can Someone tell me how to generate db script from Entity class.

**Comment by jGauravGupta** [comment]
Hi @Manoj-Madushantha ,

To generate SQL, first goto JPA Modeler > Right click > Visualize DB > View SQL

![a1](https://user-images.githubusercontent.com/15934072/44698573-16455f80-aa9e-11e8-823f-2f3c09f5ba6f.gif)

**Comment by striderm** [comment]
Thank you very much mr. Jgaurav for your help.
