### ISSUE TITLE
Update diagram from external modified Beans class or DB

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#199]
Once created there's no way to update due to changes on database and/or Entity classes. I have to delete and re-create.

**Comment by pembertonc** [comment]
Quite agree.  It would be nice to have a way to customize the Controller and Facade classes as well.   or be able to set a check override or not override for the Facade and controller classes associated with an Entity class.
I have extended a few of the Facade Classes, and modified the some of the create classes but its to easy to loose these changes in a generate.
So way to preserve the modifications of move them into the Model would be good.

A Fan and user.
Cedric Pemberton

**Comment by jGauravGupta** [comment]
To update the diagram, drag the specific java class from project tab / database from service tab and drop in the modeler diagram.

In future, functionality will be improved further with silent diagram update on class save.
