### ISSUE TITLE
Netbeans reports "Slowness detected for 20-30 s"

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#204]
Hi!
Jeddict became very slow, almost each action leads to Netbeans reports "Slowness detected for 20-30 s"
I canot attach model, but send  by private email.

**Comment by jGauravGupta** [comment]
Email : gaurav.gupta.jc@gmail.com

Are you using workspace functionality ?

**Comment by slavb18** [comment]
Checked "Main" in workplaces

**Comment by slavb18** [comment]
with limited workspace it more  responsive

**Comment by slavb18** [comment]
Will use workspaces, thanks
