### ISSUE TITLE
The field type of generated entity

### ISSUE THREAD

**Issue by herryliq** [jeddict/jeddict#205]
I used jeddict with NetBeans that the generated result looks very well except the follows problem:

The field type of entity was generated with int, double, float and so on, with this case, when create new object, the field will be used with default value, for example if type is int, the value is 0.
when use this object  insert or update to database, can not use the default value of table.

Generally, I hope the code will be generated like
```java
 public class CityAirport implements Serializable {
	@Column(name="is_delete")
	private **Integer** isDelete;

	@Column(name="is_locked")
	private **Integer** isLocked;
}
```
not like
```java
 public class CityAirport implements Serializable {
	@Column(name="is_delete")
	private **int** isDelete;

	@Column(name="is_locked")
	private **int** isLocked;
}
```
If the table field have not null attribute, the entity was generated with int,,
if the table field don't have not null attribute, the entity was generated with Integer,

**Comment by jGauravGupta** [comment]
You can always change the type of attribute from int to Integer : Properties > FieldType > DataType

**Comment by herryliq** [comment]
@jGauravGupta I can not find the setting entry, can you give me the more detail?

**Comment by jGauravGupta** [comment]
![generat1075](https://cloud.githubusercontent.com/assets/15934072/26650586/8557a744-4667-11e7-867a-cc4dff2f9f66.gif)
