### ISSUE TITLE
Jeddict install error due to Docker UI version

### ISSUE THREAD

**Issue by nureyev** [jeddict/jeddict#208]
Jeddict relies on an older Docker UI plugin version (201609300101) or 1.0.1. The newer version 1.0.2 released on 5/19/17 prevents Jeddict from being installed.

Also, thanks for developing Jeddict.

**Comment by jGauravGupta** [comment]
Please install v4.2.2 
https://github.com/jeddict/jeddict/releases/tag/4.2.2

**Comment by jGauravGupta** [comment]
Please install v4.2.2
https://github.com/jeddict/jeddict/releases/tag/4.2.2

**Comment by nureyev** [comment]
I just tested it. I seems to be working correctly. Thank you very much.
