### ISSUE TITLE
Generating projects on NetBeans 8.2 is slow

### ISSUE THREAD

**Issue by lynguo** [jeddict/jeddict#209]
hi，I am very confused,Generating a project is very slow when i use  jdk8 、netbean8.2 and jeddict 2.5  . I would like to  know whether it is my computer problem, if not, can tell me about the reasons?

**Comment by jGauravGupta** [comment]
Can you please share the modeler file. Are you using workspace functionality ?

**Comment by jGauravGupta** [comment]
This ticket has been closed due to insufficient detail.
