### ISSUE TITLE
Simplify plugin installation

### ISSUE THREAD

**Issue by chrisknoll** [jeddict/jeddict#211]
Hi, @jGauravGupta,
I'm very much enjoying using your plugin, but I wanted to file an issue about the installation process.  

I've had to update the plugin about 3 times, and each time, it is quite a headache tracking down the individual plugins to uninstall so that I can perform the update.  I can tell you have a very component-oriented mindset around your architecture for the jpa plugin, but I think at some point the robust architecture that you have adopted to make your life easier (or development easier) is making it quite a headache for the plugin-consumer such as myself.

Is there any chance that the 25 individual plugins can be combined into 2 or 3 plugins?  Maybe you can implement a deploy build process that wraps all those individual plugins that are highly componetnized,  into one plugin that is simple to install and uninstall.

At the very least, could you either assign a category to the plugins so that they can be found easier, or prefix the plugin name with something (like jCode) that would also be easier to identify and remove when a new update is being installed.

Thank you for your hard work!

-Chris

**Comment by jGauravGupta** [comment]
> I've had to update the plugin about 3 times
Have a look [https://jeddict.github.io/page.html?l=tutorial/Installation], all plugin installed in single time. Can you share the detail about 3 times installation.

>it is quite a headache tracking down the individual plugins to uninstall 
Just install the latest plugin, don't need to uninstall it, NetBeans will take care for update.

> I can tell you have a very component-oriented mindset around your architecture for the jpa plugin
Share the detail

>headache for the plugin-consumer such as myself
I agree installation process in not good, it should be automated.
The automated installation part is already done but requires some testing so currently disabled,
REF:
https://github.com/jeddict/jeddict/tree/master/Installer
https://github.com/jeddict/jeddict.github.io/blob/master/updates.xml 

>Is there any chance that the 25 individual plugins can be combined into 2 or 3 plugins
Not sure

>At the very least, could you either assign a category to the plugins so that they can be found easier, or prefix the plugin name with something (like jCode) that would also be easier to identify and remove when a new update is being installed.
Sure agreed for category, but again you don't need to remove the existing installed plugin.

**Comment by chrisknoll** [comment]
Hi, thanks for the reply.  

Re: 3 times installation.  I am saying I've updated your plugin 3 times, each time I update, i need to find the correct plugins to remove so that I can install the latest update.  You realize that you've made 9 releases since march 2017?  I've updated to 3 of them, the latest being 4.2.2.

Re: no need to install.  Per the instructions you poimted me to, This is a direct quote from the install instructions: 
> Be sure to remove any existing installation of the Jeddict plugin. Failure to do so will most likely cause installation / execution problems.

Re: component-oriented mindset: I'm just pointing out that a plugin which serves 1 purpose (JPA modeling) is split out across 25 plugins.  I understand that developing complex code is easier to manage and maintain when it's in components, but  it's cumbersome to install 25 plugins every update.

Re: installer: I'm not sure what I can do with that.

Re: assigning categories: That'd be easier to find the plugins when you want to remove them.

**Comment by jGauravGupta** [comment]
Apologies for old documentation. I remember last year when developer migrating to NetBeans 8.2 they are getting issue so I updated the doc for uninstallation . Here is new update [https://jeddict.github.io/page.html?l=tutorial/Installation] : 
> You don't need to uninstall any existing plugin for the update except for some special case like instruction available in Jeddict README.md specific to release or getting issue after migration to new NetBeans IDE version.

I agree single plugin not only make your life easier but also mine. But in case (more than 1 plugin + not required to uninstall + once category will be applied), then number of plugin will not matter for end user.

Thanks for reporting the issue :)

**Comment by jGauravGupta** [comment]
From the next release Update Center functionality will be available.

**Comment by jGauravGupta** [comment]
Here is the update center detail : 
https://jeddict.github.io/page.html?l=p/download
https://jeddict.github.io/page.html?l=p/ucinstallation
