### ISSUE TITLE
Add a description field to "Create new Named Query"

### ISSUE THREAD

**Issue by vitavitall** [jeddict/jeddict#217]
Add a description field to "Create new Named Query".

**Comment by jGauravGupta** [comment]
Would you please consider submitting a pull request?

**Comment by vitavitall** [comment]
![screen3_adddescription_good](https://user-images.githubusercontent.com/17187877/27368152-f58a4e9a-5661-11e7-80de-c44b3a1d9445.jpg)

**Comment by jGauravGupta** [comment]
Yeah right, If you like to consider submitting a pull request, here are important file

1. jeddict\JPA Modeler\src\org\netbeans\jpa\modeler\properties\named\query\NamedQueryPanel.java
2. jeddict\JPA Modeler\src\org\netbeans\jpa\modeler\properties\named\nativequery\NamedNativeQueryPanel.java
3. jeddict\JPA Modeler\src\org\netbeans\jpa\modeler\properties\PropertiesHandler.java
