### ISSUE TITLE
Add a new item "Variable Type" - Empty

### ISSUE THREAD

**Issue by vitavitall** [jeddict/jeddict#220]
It is necessary to add your annotations:
`@XmlElement(namespace = "urn:address:addressType")`

**Comment by vitavitall** [comment]
Because of specific tasks.
Need to create an `@XmlElement` annotation with the attributes manually.
Example: `@XmlElement(namespace = "urn:address:addressType")`

For this reason need:
New item "Variable Type" - None

=> When generating the code, the `@XmlElement` annotation will not be created.

**Comment by jGauravGupta** [comment]
Please attach the sample modeler file.

**Comment by vitavitall** [comment]
[ClientNow.java.txt](https://github.com/jeddict/jeddict/files/1118797/ClientNow.java.txt)
[ClientRequired.java.txt](https://github.com/jeddict/jeddict/files/1118798/ClientRequired.java.txt)
[model.jpa.txt](https://github.com/jeddict/jeddict/files/1118805/model.jpa.txt)

\+ Pattern was not created in the class.

**Comment by jGauravGupta** [comment]
Issue detected for @XmlElement but For Pattern , you can use BeanValidation properties.

```
            <jpa:basic attribute-type="String" v="true" name="countrycode" id="_149906726779591">
                <jpa:an e="true" n="@XmlElement(namespace = &quot;urn:ru:meta:address:addressType&quot;)"/>
                <jpa:xe nillable="false" required="false"/>
                <jpa:bv>
                    <jpa:pt r="[0-9]{3}"/>
                </jpa:bv>
                <jpa:column name="COUNTRYID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:basic>
```
