### ISSUE TITLE
Generating MVC project without JSP viewer fails to create some classes

### ISSUE THREAD

**Issue by nureyev** [jeddict/jeddict#225]
If an MVC project is generated without the JSP viewer the following files are not created:

controller.util.ErrorBean (src/main/java/controller/util/ErrorBean.java)
controller.util.ValidationUtil (src/mail/java/controller/util/ValidationUtil.java)

These are with the default paths provided in the generator.

**Comment by jGauravGupta** [comment]
Would you like to fix it by PR :)

**Comment by nureyev** [comment]
I can have a look, but I have a database model I need to have ready by Tuesday. After that I think I can find some time if that's ok?

**Comment by jGauravGupta** [comment]
Welcome :) , Happy to help you with the project structure and setup. This link will help you : https://jeddict.github.io/page.html?l=tutorial/Contribute

**Comment by nureyev** [comment]
Thanks :) I'll check it out and see what I can figure out. If there's any problems I'll ask.

**Comment by jGauravGupta** [comment]
Sure.
And the MVC Project Link : https://github.com/jeddict/jCode/tree/master/MVCCodeGenerator

**Comment by jGauravGupta** [comment]
Issue Fixed : https://github.com/jeddict/jeddict-extensions/commit/bb4acedb6f1813550b9c5d367702e083500a3431
