### ISSUE TITLE
installing fails for JPA modeler

### ISSUE THREAD

**Issue by MHTaleb** [jeddict/jeddict#228]
My netbeans :
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_131; Java HotSpot(TM) 64-Bit Server VM 25.131-b11
Runtime: Java(TM) SE Runtime Environment 1.8.0_131-b11
System: Windows 10 version 10.0 running on amd64; Cp1252; fr_FR (nb)
User directory: C:\Users\taleb\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\taleb\AppData\Local\NetBeans\Cache\8.2

I tried with two version of JEddict  4.2.3  and  4.3

the modules that I can't enable are

-  JPA modeler

-  JPA classes reverse engeneering

-  DB Modeler

-  JSON B Modeler

-  Database Reverse Engeneering

-  ORM Converter

**Comment by jGauravGupta** [comment]
Are you manually installing or through update center ?

**Comment by MHTaleb** [comment]
I used bouth methods
first I prefered to use the update center but no success
then I removed the update center and the downloaded JEddict
then I used the manual solution but the same issue

for update center I m using :
https://github.com/jeddict/uc/releases/download/8.2.P2/updates.xml

what should I do

my computer system is new there is only netbeans and java .

2017-07-07 5:27 GMT+02:00 Gaurav Gupta <notifications@github.com>:

**Comment by jGauravGupta** [comment]
Can you share the version of NetBeans IDE.
Removal of the update center does not help. You have to uninstall the plugin.

As per record : https://github.com/MHTaleb/YacineAutoEcole/blob/ffa1c62d9fea8642e7dc5d7c8e30960c124ebf97/src/main/java/entity/newJPADiagram.jpa
You are existing user of Jeddict. So looks like you are migrating from older to new NetBeans version and you have imported all settings of older NetBeans to new NetBeans IDE. If this is the case then , Please uninstall all plugin.

**Comment by MHTaleb** [comment]
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_131; Java HotSpot(TM) 64-Bit Server VM 25.131-b11
Runtime: Java(TM) SE Runtime Environment 1.8.0_131-b11
System: Windows 10 version 10.0 running on amd64; Cp1252; fr_FR (nb)
User directory: C:\Users\taleb\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\taleb\AppData\Local\NetBeans\Cache\8.2

2017-07-07 16:48 GMT+02:00 Gaurav Gupta <notifications@github.com>:

**Comment by MHTaleb** [comment]
as  I mentioned I do formated my computer my win 10 is a new install I was
using netbeans 8.1 in my previous install but now in this new windows
install i want to use netbeans 8.2 with jeddict 4.3

I do removed the update center and the installed plugins but no success


2017-07-07 18:31 GMT+02:00 Taleb Mohammed Housseyn <talcorpdz@gmail.com>:

**Comment by jGauravGupta** [comment]
It's really wired, Can you also share the screenshot of issue , plugin panel etc.

**Comment by MHTaleb** [comment]
what do you think abot giving you access using teamviewer 7 ???

**Comment by MHTaleb** [comment]
Hi Gaurav
It is wired I did remove My netbeans then I did go to My AppData/roaming
and removed all netbeans entries then i cleared my regestry
then a reinstalled netbeans and I tried to install JEDDICT by update center
and now is working fine
don't know why but is fine right now

thank you so much for the response


2017-07-07 19:16 GMT+02:00 Gaurav Gupta <notifications@github.com>:
