### ISSUE TITLE
Collection with initial Value "new ArrayList" Import "java.util.ArrayList;"  is missing

### ISSUE THREAD

**Issue by Mobidat** [jeddict/jeddict#233]
when choosing implementation Type in Property-Window i.e. "ArrayList", I thought the collection is  initialised like this
`private List<MyEntity> myEntities = new ArrayList();`
but nothing happened. So I write to option DefaultValue "new ArrayList()". Now the code is generated as expected. But the Import of the java.util.ArrayList; is missing. So I have to travel through all my classes to fix it. 
I also miss the Service class generation. CDI support is nice - but why do you realize it not as an additional option and leave the old solution for user without CDI knowledge?

**Comment by jGauravGupta** [comment]
- Please use Full qualified class "new java.util.ArrayList()".

- In case of implementation Type, it should generate null check in getter. (currently not working) 
 Ref : #219 

- Only JPA repository classes are migrated to CDI. 

If possible, User should always ready to adapt new technology. In upcoming release generated code will only support Java EE 8 environment. It is really difficult to maintain support for multiple option, so user can use older version of plugin in such a case.
