### ISSUE TITLE
Authorities endpoint 404 not found

### ISSUE THREAD

**Issue by ian-a-hickey** [jeddict/jeddict#236]
I'm using latest Jeddict, Angular 4, MySql, Payara

I have found everything is working as expected except the user.service.ts#authorities() method is referencing the Url /api/users/authorities. I believe it should reference /resources/api/users/authorities like all the other endpoints that I can find. Because it can't find the authorities endpoint, you can't create / update a user as there is no way to populate the select. I think updating the userService method to something like this would fix it (if that endpoint exists):

authorities(): Observable<string[]> {
        return this.http.get(`${this.resourceUrl}/authorities`).map((res: Response) => {
            const json = res.json();
            return <string[]> json;
        });
} 

Additionally, I'm not finding that resource defined anywhere so an endpoint may need to also be added.

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue :)
