### ISSUE TITLE
EmbbededId Class equals method code generation error.

### ISSUE THREAD

**Issue by pembertonc** [jeddict/jeddict#238]
Greetings,

The equals operation in the generated embeddedId Classes contains 

 final BusinessConcernPK other = (BusinessConcernPK) obj;
        if (!java.util.Objects.equals(this.getFarmer().orElse(null), other.getFarmer().orElse(null))) {
            return false;
        }
        if (!java.util.Objects.equals(this.getEnterpriseType().orElse(null), other.getEnterpriseType().orElse(null))) {
            return false;

however: the getXXX Methods eg. getFarmer() looks like this;
 public Optional<String> getFarmer() {
        return this.farmer;
    }

This happens when i switched to optional return types as default.

**Comment by jGauravGupta** [comment]
Please attach the sample modeler file to reproduce it.

**Comment by pembertonc** [comment]
Please find attached a zipped copy of the Modeler file.

Thank you
[SVG-NAITS-2017-08-29.zip](https://github.com/jeddict/jeddict/files/1260135/SVG-NAITS-2017-08-29.zip)
