### ISSUE TITLE
DBConnectionNotFound

### ISSUE THREAD

**Issue by JTMMartins** [jeddict/jeddict#239]
##### **Overview of the issue**

I was working perfectly modeling a Database...Exited NetBeans 8.2.

Later when returning, I tried the Visualize DB Option, but all I can get is : DBConnectionNotFound. however the connection is there..and deleting and recreating does not solve this. 
(Using derby,ubuntu & netbeans 8.2)

When opening the visualize Db, it immediately requests the User and Password, and selecting OK or CANCEL produces the same message.

Any hints ?
Many thanks

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue.
For a temporary fix,  just open the modeler file (Right click on file > Open) and search the "<db>" tag and remove it. 
I guess the details available in "<db>" tag and active connection is not matching.
