### ISSUE TITLE
Does it possible to automate anotations generation by type

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#240]
Does it possible to automate anotations generation by type

E.g. for type LocalDate automatically add annotation 
```java
@XmlSchemaType(name = "date")
```
Is there such base funtionality or using own plugin, etc?

**Comment by slavb18** [comment]
Can this 
https://jeddict.github.io/page.html?l=tutorial/Contribute
be used to extend class generation?

**Comment by jGauravGupta** [comment]
Yes,  you can add this functionality with this [https://jeddict.github.io/page.html?l=tutorial/Contribute]

**Comment by slavb18** [comment]
thanks
