### ISSUE TITLE
Does it posible to generate "Export image" from command line / maven

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#241]
Hi!

Does it posible to generate "Export image" from command line / maven ?

**Comment by jGauravGupta** [comment]
Not possible currently, but if you are interested re-open the ticket and contribute.

**Comment by slavb18** [comment]
What do you think about converting jeddict someday to maven netbeans module preject?
Is there any major obtacles, which could prevent such conversion, or this is simply not need,
or there is no time for that?

**Comment by jGauravGupta** [comment]
there is no time for that but would love to see it as maven NetBeans module project :)
