### ISSUE TITLE
Does copy-and-paste reverse-engeener entities intended to work?

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#242]
Hi!

Does copy-and-paste reverse-engeener entities intended to work?

Tryed in jeddict 4.4.1 entity class drag and drop from projects panel to model, copy and paste,
and no errors and nothing done.

**Comment by jGauravGupta** [comment]
This is cool feature but not yet supported.

Duplicate of :  #133  & #195

**Comment by slavb18** [comment]
thanks, sorry
