### ISSUE TITLE
Disable the creation of persistence.xml

### ISSUE THREAD

**Issue by gbourant** [jeddict/jeddict#246]
Hello ,

When we choose to Generate Source Code the persistence.xml is created or if the file already exists , it appends the "DEFAULT_PU".

It would be great if we could disable the creation or the appendance of persistence.xml

Thanks.

**Comment by jGauravGupta** [comment]
Update the Persistence Unit name with already existing PU name of persistence.xml. So it will not create the new PU.
**Click on the diagram > Properties > Basic Properties > Persistence Unit name**

**Comment by gbourant** [comment]
Hello @jGauravGupta ,

I did as you have said but , it still adds class tags. If it's possible to disable the update of the current Persistence Unit .

Thank you.

**Comment by jGauravGupta** [comment]
Will add this feature to next release :)
