### ISSUE TITLE
Cannot Generate Project Following Angular instructions

### ISSUE THREAD

**Issue by felipe-alves-moraes** [jeddict/jeddict#248]
##### **Overview of the issue**
Hi, I´m trying to follow the instructions to generate the Angular App, but I´m being able to do it.

##### **Expected Outcome**
After I click 'Build with dependencies' I was expecting to see the build success message. But instead I keep receiving the following error:

##### **Current Outcome**

`--- frontend-maven-plugin:1.3:yarn (yarn install) @ shoppingsystem ---
Running 'yarn install' in D:\bitbucket\estudos\ShoppingSystem
yarn install v0.18.1
info No lockfile found.
error Error parsing JSON at "D:\\bitbucket\\estudos\\ShoppingSystem\\package.json", "D:\\bitbucket\\estudos\\ShoppingSystem\\package.json: Unexpected end of JSON input".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

##### **Steps to Reproduce**(Only for bug reports) 
I just followed the tutorial until the Deploy section.

##### **Jeddict Version(s)**
v4.4.1

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue.
Can you please share the package.json & modeler file and can you also generate the project with npm option.

**Comment by felipe-alves-moraes** [comment]
Hi @jGauravGupta, the `package.json` generated is empty. Here is my model JPA file.

[CartModel.zip](https://github.com/jeddict/jeddict/files/1367064/CartModel.zip)

By generate the project with npm option, you mean run the `npm install`? If so, I got an error saying that the package.json file is empty.

**Comment by felipe-alves-moraes** [comment]
Just updating, using the version 4.6.1 it works like a charm 😄

**Comment by jGauravGupta** [comment]
By generate the project with npm option mean => At the generation time in Angular tab select npm option.

Please try with the latest version of jeddict.

**Comment by felipe-alves-moraes** [comment]
Oh, got it, I downloaded the last version of jeddict and I saw that in Angular now appears the npm option, I'll do some tests and give you the feedback as soon as I finish it.

Thanks.

**Comment by felipe-alves-moraes** [comment]
@jGauravGupta is it possible to select the Java EE version that we want to generate the project? I tried with the last version of jeddict and it generates fine this time, but I cannot select the Jave EE version.

**Comment by jGauravGupta** [comment]
It was difficult to manage multiple version of Java EE so by default it now supports the latest version (8.0).
So not possible to select Java EE version.

Note : You can use Payara 5-alpha1 to run the generated source code and after few months replace with GA release.

**Comment by felipe-alves-moraes** [comment]
Good to know. I'll do this then, thanks for the support

**Comment by felipe-alves-moraes** [comment]
Just as a update I was able to do it using Payara 5, I also tried with Glassfish 5 but got some errors and wasn't able to deploy it.

I guess this issue can be closed, right?

**Comment by jGauravGupta** [comment]
Not sure about Glassfish 5, logically it should work on any Java EE 8 server because generated source code is following standard and also tested on Payara 5 alpha-1/snapshot.

Closing this as Angular issue solved :)
