### ISSUE TITLE
@NamedQueries not generated in version 4.6 and 4.6.1, working in 4.4.1

### ISSUE THREAD

**Issue by ReneKuzica** [jeddict/jeddict#249]
NB8.2 (build 201609300101), JDK8, Jeddict 4.4.1, 4.6, 4.6.1
@NamedQueries tag is missing (not generated) by newer version of Jeddict.

Let's model an entity Altitude with two properties altitude (int) and timetick (java.util.Date)
Open entity properties and select all possible Named Queries to be generated.

I was expecting (as in version 4.4.1):
@Entity
@NamedQueries({ @NamedQuery(name = "Altitude.findAll", query = "Select e from Altitude e"),
    @NamedQuery(name = "Altitude.findByAltitude", query = "Select a from Altitude a where a.altitude=:altitude"),
    @NamedQuery(name = "Altitude.findByTimetick", query = "Select a from Altitude a where a.timetick=:timetick") })
public class Altitude{...}

I got (version 4.6 and 4.6.1):
@Entity
@NamedQuery(name = "Altitude.findAll", query = "Select e from Altitude e"),
@NamedQuery(name = "Altitude.findByAltitude", query = "Select a from Altitude a where a.altitude=:altitude"),
@NamedQuery(name = "Altitude.findByTimetick", query = "Select a from Altitude a where a.timetick=:timetick")
public class Altitude{...}

**Comment by jGauravGupta** [comment]
Recent version of Jeddict supports Java EE 8, so container annotation (for e.g NamedQueries) is not required any more.
For more info : https://www.slideshare.net/jGauravGupta/rapid-development-tools-for-java-ee-8-tut2998/23?src=clipshare
