### ISSUE TITLE
Properties window stays open

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#251]
##### **Overview of the issue**

Properties window stays open when moving from the JPA diagram to another tab i.e. source.

##### **Expected Outcome**

I would expect it to minimize like the palette window.

##### **Current Outcome**

Properties window stays open.

##### **Steps to Reproduce**(Only for bug reports) 

1. Create/Open a diagram.
2. Open another file in the IDE (i.e source file)
1. While in the Diagram window, select the tab of the file source.
1. Notice the properties window stays open while the palette is minimized.

##### **Jeddict Version(s)**

4.6.1

**Comment by javydreamercsw** [comment]
It's always good to link commits to fixes, but thanks for fixing it. When is this being released?

**Comment by jGauravGupta** [comment]
Yes It's always good but In current release, unfortunately 3 ticket missed the commit link,
Please install the Jeddict v4.8 and confirm the fix : https://github.com/jeddict/jeddict/releases/tag/4.8

**Comment by jGauravGupta** [comment]
https://github.com/jeddict/NBModeler/commit/fc7d037101f91c083fffa95bae81c577657c9dae

**Comment by javydreamercsw** [comment]
Verified as working. Thanks a lot!
