### ISSUE TITLE
Error is generated NamedQueries 

### ISSUE THREAD

**Issue by pembertonc** [jeddict/jeddict#252]
##### **Overview of the issue**

Named Query generation missing the enclosing @NamedQueries annotation

##### **Expected Outcome**
More than one Named Query should be enclosed in @NamedQueries({ })

The current out put is as follows:

@NamedQuery(name = "Specie.findAll", query = "Select e from Specie e")
@NamedQuery(name = "Specie.findByName", query = "Select s from Specie s where s.name=:name")
@NamedQuery(name = "Specie.findByKingdom", query = "Select s from Specie s where s.kingdom=:kingdom")
@NamedQuery(name = "Specie.findBySymbol", query = "Select s from Specie s where s.symbol=:symbol")
@NamedQuery(name = "Specie.findByDescription", query = "Select s from Specie s where s.description=:description")

##### **Jeddict Version(s)**
jeddict version  4.4.1

**Comment by jGauravGupta** [comment]
Recent version of Jeddict supports Java EE 8, so container annotation (for e.g NamedQueries) is not required any more.

Duplicate issue #249
