### ISSUE TITLE
download does not work on a web page

### ISSUE THREAD

**Issue by tjago** [jeddict/jeddict#255]
##### **Overview of the issue**

webpage javascript potentially broken

##### **Expected Outcome**

Expected download works

##### **Current Outcome**

page does not proceed to download upon button clicked

##### **Steps to Reproduce**(Only for bug reports) 
Open 

https://jeddict.github.io/page.html?l=p/download#

Or navigate using on-site menu to go to Download section

Click button to download - nothing happens

##### **Jeddict Version(s)**

N/A
affects web-page

**Comment by jGauravGupta** [comment]
Thanks @tjago for reporting the issue.
