### ISSUE TITLE
@Id @ManyToOne db diagram mapping issue

### ISSUE THREAD

**Issue by lubriBoy** [jeddict/jeddict#265]
##### **Overview of the issue**

In a diagram with more than 40 entities, don't allows visualize database when click right  button. And from the beging with this diagram also does not show the relation edges (the lines) correctly. Shows relation fields inside entities in both sides but missing line.

##### **Expected Outcome**

It's supoused to show database diagram.

Shows the error uploaded, and when closing error window keep working as usual.

   ####

[ModelGeralJPA.zip](https://github.com/jeddict/jeddict/files/1821981/ModelGeralJPA.zip)
Just right click and select "visualize DB", and error came.

Jeddict Version: 4.4.1
Product Version: NetBeans IDE 8.2 (Build 201705191307)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_121; Java HotSpot(TM) 64-Bit Server VM 25.121-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_121-b13
System: Windows 10 version 10.0 running on amd64; Cp1252; es_AR (nb)
User directory: C:\Users\lean\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\lean\AppData\Local\NetBeans\Cache\8.2

System specs:
Notebook Asus
Intel i7-6500U CPU @ 2.50GHz  2.59GHz
RAM 16GB (15.9 usable)
64 bit
Win 10 Home
OS compilation 16299.309

![imagen](https://user-images.githubusercontent.com/37484237/37559015-8a92bffe-29fc-11e8-84f7-d5ecf04ec296.png)

**Comment by lubriBoy** [comment]
Hi @jGauravGupta,
look in this two entities: Venta & Entrada . The fields (entrada-venta) inside relation part are one edge, but line is gone. 
Now i've updated to lastest version (4.7) in this picture below.
Thank you for having answered so fast!


![image](https://user-images.githubusercontent.com/37484237/37561379-1f242926-2a2c-11e8-8659-03c8ff5a730b.png)

**Comment by jGauravGupta** [comment]
Hi @lubriBoy ,

Had you created this diagram manually (by drag-n-drop of entities) or by reverse engineering the existing class.

**Comment by lubriBoy** [comment]
First I had created three diagram separately. 
This one have the relation between "Venta-Entrada".
![image](https://user-images.githubusercontent.com/37484237/37567435-a0ab2912-2aa5-11e8-8636-ff4ca039fb31.png)


Then generate source code from all of them and I did reverse engineering from that source code to unificate all three diagram.
So, could we say it's kind of drag and drop way, no?

**Comment by jGauravGupta** [comment]
https://github.com/jeddict/jCode/commit/3dc4f52d63b497994f569b2e7295cdb0d4b8ca66
