### ISSUE TITLE
Error deploying

### ISSUE THREAD

**Issue by araoul** [jeddict/jeddict#266]
When I tried to build my project I have this error:  

" Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (install node and npm) on project tontine: Could not extract the npm archive: Could not extract archive: 'C:\Users\RAOUL\.m2\repository\com\github\eirslett\npm\5.3.0\npm-5.3.0.tar.gz': EOFException -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging."

**Comment by jGauravGupta** [comment]
Can you share the maven version detail. If you are using NetBeans IDE bundled maven then please upgrade to maven v3.5.0+ : Tools > Option > Java > Maven > Maven Home

**Comment by jGauravGupta** [comment]
Hi @araoul ,

May you confirm this issue with v4.8 too : https://github.com/jeddict/jeddict/releases/tag/4.8
