### ISSUE TITLE
Created entities have errors

### ISSUE THREAD

**Issue by javydreamercsw** [jeddict/jeddict#269]
##### **Overview of the issue**
Creating the entities create bad classes that can't be compiled.

##### **Expected Outcome**

Fully working classes.

##### **Current Outcome**

Class has a lot of what looks to be contents of template files.

##### **Steps to Reproduce**(Only for bug reports) 

Generate source from attached file.

##### **Jeddict Version(s)**

4.8.2
[DB.jpa.zip](https://github.com/jeddict/jeddict/files/1974556/DB.jpa.zip)

**Comment by jGauravGupta** [comment]
Hi @javydreamercsw ,

Can you share the screenshot of error, as the class generated by this diagram looks good and compiled without any issue.

**Comment by javydreamercsw** [comment]
I noticed that for some reason I had two copies of each plugin. I added the update center of the last release. Removed everything and now NetBeans is in a state I can't recover from.

**Comment by javydreamercsw** [comment]
Looks like the issue was that the IDE was running on JDK 10. Once I changed that it worked fine.
