### ISSUE TITLE
OneToMany imporvement

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#271]
Hi!

I constantly add two snippets to OneToMany relation
```xml  
                <jpa:snp loc="PRE_GETTER" e="true">        if (this.docfiles == null) {
            this.docfiles = new ArrayList&lt;&gt;();
        }</jpa:snp>
                <jpa:snp loc="AFTER_METHOD" e="true">    public Document addDocfiles(Docfile docfile) {
        docfile.setDocument(this);
        getDocfiles().add(docfile);
        return this;
    }</jpa:snp>
```

See this generated class
https://github.com/ilb/jparestresource/blob/master/jparestresource/jparestresource-web/src/main/java/ru/ilb/jparestresource/model/Document.java

First one to initialize list if it is empty, like jaxb does:
```java
    public List<Docfile> getDocfiles() {
        if (this.docfiles == null) {
            this.docfiles = new ArrayList<>();
        }
        return this.docfiles;
    }
```

second to add  bidirectional relation and set many-to-one 
```java
    public Document addDocfiles(Docfile docfile) {
        docfile.setDocument(this);
        getDocfiles().add(docfile);
        return this;
    }
```

Do you see worth implementing this in jeddict?

**Comment by jGauravGupta** [comment]
Jeddict already generates these snippets for relationships (install Jeddict v4.4+)

**Comment by slavb18** [comment]
Sorry, I don't understand.
If I write such snippets by hand, they are working 
But I am asking about feature to automatically generate such code on Many-To-One relationships, without writing snippets by hand.
E.g. for every collection generate addCollectionname() method, which populates many to one side,
and initialize collection in getter.
I updated to v4.8.4 and do not see such behavior.
Here is my model.jpa

https://github.com/ilb/jparestresource/blob/master/jparestresource/jparestresource-web/src/main/resources/META-INF/model.jpa

It contains manually written snippets, but if I remove them, no methods generated

**Comment by slavb18** [comment]
Sorry. I removed and added relationship and it worked. Thanks!
