### ISSUE TITLE
Multiple named queries generates wrong code

### ISSUE THREAD

**Issue by grahams777** [jeddict/jeddict#274]
##### **Overview of the issue**

Problem statement: 
  Netbeans 8.2 installation corrupted.
  Uninstalled NB 8.2 with re-install
  Added jeddict as per latest version
  Now generates code for each query incorrectly
  Pre-corruption it worked correctly using @NamedQueries({

@Entity
@NamedQuery(name = "Test.findAll", query = "Select e from Test e")
@NamedQuery(name = "Test.findByAttribute", query = "Select t from Test t where t.attribute=:attribute")

public class Test {

##### **Expected Outcome**
NOTE: sample expectation - does not match code above
@Entity
@NamedQueries({
    @NamedQuery(name="Country.findAll",
                query="SELECT c FROM Country c"),
    @NamedQuery(name="Country.findByName",
                query="SELECT c FROM Country c WHERE c.name = :name"),
}) 

##### **Netbeans Version**                                         
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_162; Java HotSpot(TM) 64-Bit Server VM 25.162-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_162-b12
System: Windows 10 version 10.0 running on amd64; Cp1252; en_ZA (nb)
User directory: C:\Users\pcc\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\pcc\AppData\Local\NetBeans\Cache\8.2

**Comment by jGauravGupta** [comment]
Duplicate ticket #252 , #249 

Now, Jeddict (4.5+ version) provide the supports for Java EE 8, so container annotation (for e.g NamedQueries) is not required any more. You can still download the older version for Java EE 7 (if required) : https://jeddict.github.io/page.html?l=p/download

For more info : 

- https://www.slideshare.net/jGauravGupta/rapid-development-tools-for-java-ee-8-tut2998/23?src=clipshare
- https://www.youtube.com/watch?v=HduJZxtmOQQ
