### ISSUE TITLE
Custom Snippet support in Java editor

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#275]
What do you think about some way of autoproxing of implementation methods in entities, additionally to snippets?
Wouldn't it simplify snippet writing, because basic Netbeans capabilities to write code could be used in this case?

Example

Assuming there is entity 'SomeEntity', and package contains hand-written  (possible package protected) 'SomeEntityImpl' class with static implemetation methods.
````
class SomeEntityImpl {
    public static void oneMethod(SomeEntity someEntity);
    public static boolean secondMethod(SomeEntity someEntity, boolean param);
}
````

leads to code proxy generation in SomeEntity class:

````
public class SomeEntity {
    ....
    public void oneMethod() {
        SomeEntityImpl.oneMethod(this);
    }
    
    public boolean secondMethod(boolean param) {
        return SomeEntityImpl.secondMethod(this, param);
    }    
}
````

**Comment by jGauravGupta** [comment]
In my view, developer will not prefer the above proxy way. Can you share the scenario (and diagram) for mostly used snippet code. Perhaps it would be great, if usage of snippet code functionality will be reduced somehow (possibly partially overwriting the entity file etc).

**Comment by slavb18** [comment]
Snippet editor is not true code editor, it lacks code completion, auto-imports, e.t.c,
for long snippets I prefer this way of writing, e.g. merging of collections (implementing custom setSomeEntities method which merges child entities using some key, e.t.c.)

This is example of lengthy method, which is hard to write in snipets.

```java
    public static void setVariableBudgets(Clause clause, List<VariableBudget> variableBudgets) {

        if (variableBudgets == null) {
            variableBudgets = new ArrayList<>();
        }

        Map<Integer, VariableBudget> sourceMap = variableBudgets.stream()
                .collect(Collectors.toMap(vb -> VariableBudgetUtil.getMergeHash(vb), Function.identity()));

        ListIterator<VariableBudget> li = clause.getVariableBudgets().listIterator();
        while (li.hasNext()) {
            VariableBudget vb = li.next();
            int typeHash = VariableBudgetUtil.getMergeHash(vb);
            if (!sourceMap.containsKey(typeHash)) {
                li.remove();
            } else {
                VariableBudgetUtil.copyTo(sourceMap.get(typeHash), vb);
                sourceMap.remove(typeHash);
            }
        }
        List<VariableBudget> newItems = sourceMap.values().stream()
                .map(sourceItem -> VariableBudgetUtil.copyTo(sourceItem, null).withClause(clause))
                .collect(Collectors.toList());
        clause.getVariableBudgets().addAll(newItems);
    }
```

Another example is "copyTo" method, which copies single entity.

Goal of this to make entities with logic, especially useful in case of entity  inheritance.
But since there is no light way to write snippets (and my way is not so easy), I write inherited "controllers" - every entity has its own "controller" with logic, like

```java
controller  = controllerFactory.getController(entity);
controller.doSomeMethod(entity);
```

instead of just 

```java
entity.doSomeMethod();
```

**Comment by slavb18** [comment]
Another option is to use some annotation or comment block like

/* BEGIN HAND-WRITTEN-CODE */
{there is code which is not overwritten from jeddict. E.g. jeddict copies this code and writes back.
But what to do with imports on top of file, they will be lost, if Jedict not copies them}
/* END HAND-WRITTEN-CODE */

**Comment by jGauravGupta** [comment]
Jeddict v5.0 automatically detects the custom snippet in the existing source code file during generation process and rewrites back to the source code file.
Automatic sync can be disable in settings.
In case, If custom snippet is lost during generation process, please report the issue.

**Comment by slavb18** [comment]
Thank You!
