### ISSUE TITLE
JPA-Diagram Visualize DB not working

### ISSUE THREAD

**Issue by sandious** [jeddict/jeddict#276]
##### **Overview of the issue**
Within a JPA-Diagramm right mouse-klick selecting Visualize DB -> Bug-Window comes up.

##### **Expected Outcome**
I have modified my Diagramm [added a new basic attribute to one table ] wanted to synchronize it with existing entity code.
##### **Steps to Reproduce**(Only for bug reports) 
netbeans 8.2

##### **Jeddict Version(s)**
4.9

**Comment by jGauravGupta** [comment]
Can you share the modeler file ?

**Comment by jGauravGupta** [comment]
This ticket has been closed due to insufficient detail.
