### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by codegagan** [jeddict/jeddict#282]
##### **Overview of the issue**

Maven build fails right after code generation: 

Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) on project testjeddict: The plugin com.github.eirslett:frontend-maven-plugin:1.6 requires Maven version 3.1.0 -> [Help 1]

##### **Expected Outcome**

Build without any custom changes should succeed.

##### **Current Outcome**

Maven version error

##### **Steps to Reproduce**(Only for bug reports) 

- Create new maven web application project.
- Create a new jpa model
- Create a simple entity say 'Employee' with attributes like 'Name' , 'Age' and 'City'
- Generate code with Monolith, CDI, Rest and Angular 6
- Run the project
- Maven build fails

##### **Jeddict Version(s)**
Jeddict 5.0
Netbeans 8.2

**Comment by jGauravGupta** [comment]
As shown in error message, please use maven 3.5.0 or higher version. 

NetBeans ships with older version of maven. You may update it by adding new location of maven in Options.

**Comment by codegagan** [comment]
The above suggestion worked, now another hurdle:

Running 'yarn run webpack:build' in C:\Users\singhg23\Documents\NetBeansProjects\TestJeddict
yarn run v1.3.2
$ yarn run cleanup && yarn run webpack:build:main
$ rimraf target/{aot,www}
**'rimraf' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.**
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

**Comment by codegagan** [comment]
Added below snippet manually in pom.xml to overcome above mentioned issue.

```xml
                               <execution>
                                <goals>
                                    <goal>yarn</goal>
                                </goals>
                                <configuration>
                                    <arguments>add rimraf</arguments>
                                    <yarnInheritsProxyConfigFromMaven>false</yarnInheritsProxyConfigFromMaven>
                                </configuration>
                                <id>install rimraf</id>
                                
                            </execution>

**Comment by jGauravGupta** [comment]
Doc fixed by https://github.com/jeddict/hipee/commit/2939d6e84224640b789f691577c15dadc9d842fc
