### ISSUE TITLE
Generate Source removeEntitity with double set / get 

### ISSUE THREAD

**Issue by Mobidat** [jeddict/jeddict#287]
##### **Overview of the issue**

When generating Entities with Set / List collection type, the generated removeNameEntity method is filled with double set or get prefixes:

public void removeZahlungEntity(ZahlungEntity zahlungEntity) {
        getZahlungEntities().remove(zahlungEntity);
        zahlungEntity.setsetKundeEntity(null);
    }

##### **Expected Outcome**

public void removeZahlungEntity(ZahlungEntity zahlungEntity) {
        getZahlungEntities().remove(zahlungEntity);
        zahlungEntity.setKundeEntity(null);
    }

##### **Jeddict Version(s)**

Jeddict 5.0

**Comment by jGauravGupta** [comment]
Duplicate Issue ref : #284
