### ISSUE TITLE
Generated AuthorityControllerTest Method getNonExistingAuthority() needs a String!

### ISSUE THREAD

**Issue by Mobidat** [jeddict/jeddict#289]
##### **Overview of the issue**

@Test
    @InSequence(4)
    public void getNonExistingAuthority() throws Exception {
        // Get the authority
        assertWebException(NOT_FOUND, () -> client.getAuthority(Long.MAX_VALUE));
    }

Long.MAX_VALUE is not a String

##### **Expected Outcome**

@Test
    @InSequence(4)
    public void getNonExistingAuthority() throws Exception {
        // Get the authority
        assertWebException(NOT_FOUND, () -> client.getAuthority(TestString));
    }

**Comment by jGauravGupta** [comment]
Fixed by : https://github.com/jeddict/jeddict-extensions/commit/f78208d67bcc74d17597b53bf2656a8bd89e805e
