### ISSUE TITLE
CDI Repository Entity Suffix "Service" is not compatible to Switch "generate Base App"

### ISSUE THREAD

**Issue by Mobidat** [jeddict/jeddict#290]
##### **Overview of the issue**

If somone choose the suffix <entity> Service instead of <entity> Repository and switch "generate Base App" is activated Jeddict generates two classes with the name UserService. One in the CDI Repository and one in the Service Folder. This doubled class name leads to some naming iusses in other classes.

##### **Expected Outcome**

if the CDI repo suffix Service is used show error or disable generate Base App or automatic rename UserService class in Service folder to avoid name conflicts.

##### **Jeddict Version(s)**

5.1 (a great tool tnx!)

**Comment by jGauravGupta** [comment]
Fixed by : https://github.com/jeddict/jeddict-extensions/commit/7c0a45b708c80a7f678db0e7f771c4ddcc31d28f
