### ISSUE TITLE
View DB action can called on table and not on Database

### ISSUE THREAD

**Issue by Chris2011** [jeddict/jeddict#295]
##### **Overview of the issue**

When I want to visualize the DB, I expect the action on the DB node, not on the Table node.

##### **Expected Outcome**

View DB Action should be on the DB, not on the table. On the Table, there should be View Table.

##### **Current Outcome**

View DB action appears on selecting the table and shows only the table, not the DB.

##### **Steps to Reproduce**(Only for bug reports) 

1. Open a connection
2. Select the DB
3. Right click on DB
4. No action for View DB
5. Expand DB
6. Right click on table
7. See action for View DB
8. Click on it
9. Opens the Visualizer but only for the table.

##### **Jeddict Version(s)**
NetBeans 8.2, Jeddict 5.0

**Comment by Chris2011** [comment]
Any news here?

**Comment by jGauravGupta** [comment]
Hi @Chris2011,

I agree **View DB** should be renamed to **View Table**.
But I suspect, you have missed the  **View DB** option on **Tables** node.

**Comment by Chris2011** [comment]
Ok, yes maybe but I expect this ways:
* Right click on DB Node -> View DB
* Right click on Tables Node -> View Tables
* Right clock in specific Table Node -> View Table

So Tables node shows tables instead of db in NetBeans. This is why I would expect to see View Tables, instead of View DB on the Tables Node/Folder.
