### ISSUE TITLE
NetBeans 10 support

### ISSUE THREAD

**Issue by hantsy** [jeddict/jeddict#304]
NetBeans 10  was released,  but when I added update url for NB 9 and tried to install it, got failed, similar dependencies problems with #286

**Comment by jGauravGupta** [comment]
Release artifact updated with Apache NetBeans IDE 10.0 (Build incubator-netbeans-release-380-on-20181217) compatible plugin.

[Jeddict_5.2_for_Apache_NetBeans_IDE_10.0](https://github.com/jeddict/jeddict/releases/download/5.2/Jeddict_5.2_for_Apache_NetBeans_IDE_10.0.zip)
[Jeddict_5.2_with_Apache_NetBeans_IDE_10.0](https://github.com/jeddict/jeddict/releases/download/5.2/Jeddict_5.2_with_Apache_NetBeans_IDE_10.0.zip)
