### ISSUE TITLE
Class properties are not always displayed - netbeans 8.2

### ISSUE THREAD

**Issue by vitavitall** [jeddict/jeddict#312]
##### **Overview of the issue**

Class properties are not always displayed - netbeans 8.2
It is necessary to open through the context menu

![unnamed](https://user-images.githubusercontent.com/15934072/51983133-ec192300-24bd-11e9-8ec1-13112896b9d9.png)

##### **Jeddict Version(s)**

Jeddict 5.2
NetBeans 8.2

**Comment by vitavitall** [comment]
.

**Comment by vitavitall** [comment]
.

**Comment by vitavitall** [comment]
Screenshot sent by mail

**Comment by jGauravGupta** [comment]
Can you share exception stack-trace, available on the bottom tray of the IDE.

**Comment by vitavitall** [comment]
No longer repeats. Memory size increased from 8 to 16 GB.
