### ISSUE TITLE
project build not work from nebeans ide 

### ISSUE THREAD

**Issue by masumcse1** [jeddict/jeddict#314]
##### **Build time issue**

cd E:\dev-jddict\New folder\jeddictPractice1; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_152" cmd /c "\"\"E:\\dev-jddict\\setup\\NetBeans_IDE_9.0\\java\\maven\\bin\\mvn.cmd\" -Dmaven.ext.class.path=E:\\dev-jddict\\setup\\NetBeans_IDE_9.0\\java\\maven-nblib\\netbeans-eventspy.jar -Dfile.encoding=UTF-8 install\""
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building jeddictPractice1 1.0-snapshot
------------------------------------------------------------------------

--- maven-dependency-plugin:2.6:copy (default) @ jeddictpractice1 ---

--- jacoco-maven-plugin:0.8.2:prepare-agent (jacoco-initialize) @ jeddictpractice1 ---
argLine set to "-javaagent:C:\\Users\\masum\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=E:\\dev-jddict\\New folder\\jeddictPractice1\\target\\coverage-reports\\jacoco-unit.exec"

--- maven-resources-plugin:3.1.0:resources (default-resources) @ jeddictpractice1 ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 8 resources

--- maven-resources-plugin:3.1.0:copy-resources (filter-resource) @ jeddictpractice1 ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 3 resources

--- maven-compiler-plugin:3.7.0:compile (default-compile) @ jeddictpractice1 ---
Nothing to compile - all classes are up to date

--- maven-resources-plugin:3.1.0:testResources (default-testResources) @ jeddictpractice1 ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 4 resources

--- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ jeddictpractice1 ---
Nothing to compile - all classes are up to date

--- maven-surefire-plugin:2.20.1:test (default-test) @ jeddictpractice1 ---
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.erp.app.controller.AccountControllerTest
Feb 06, 2019 11:14:16 PM fish.payara.arquillian.container.payara.CommonPayaraManager start
SEVERE: Could not connect to DAS on: http://localhost:4848 | Connection refused: connect
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.881 s <<< FAILURE! - in com.erp.app.controller.AccountControllerTest
com.erp.app.controller.AccountControllerTest  Time elapsed: 16.877 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not connect to DAS on: http://localhost:4848 | Connection refused: connect

Running com.erp.app.controller.CustomerControllerTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.erp.app.controller.CustomerControllerTest
com.erp.app.controller.CustomerControllerTest  Time elapsed: 0.001 s  <<< ERROR!
java.lang.RuntimeException: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
Caused by: org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not connect to DAS on: http://localhost:4848 | Connection refused: connect

Running com.erp.app.controller.UserControllerTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.erp.app.controller.UserControllerTest
com.erp.app.controller.UserControllerTest  Time elapsed: 0 s  <<< ERROR!
java.lang.RuntimeException: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
Caused by: org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not connect to DAS on: http://localhost:4848 | Connection refused: connect

Results:

Errors: 
  AccountControllerTest.com.erp.app.controller.AccountControllerTest » Lifecycle
  CustomerControllerTest.com.erp.app.controller.CustomerControllerTest » Runtime
  UserControllerTest.com.erp.app.controller.UserControllerTest » Runtime Arquill...

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 01:05 min
Finished at: 2019-02-06T23:14:18+06:00
Final Memory: 17M/42M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project jeddictpractice1: There are test failures.

Please refer to E:\dev-jddict\New folder\jeddictPractice1\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by masumcse1** [comment]
Please find my config file : pom.xml and nb-configuration.xml
[config.zip](https://github.com/jeddict/jeddict/files/2837736/config.zip)

**Comment by jGauravGupta** [comment]
Attached pom.xml contains 2 test profiles : **payara-ci-managed** and **payara-remote**, where payara-remote is default profile.

**payara-ci-managed :**
This profile installs a Payara server and start up the server per sample.

**payara-remote :** 
This profile doesn't manage the lifecycle of a container but binds to an already running container means it depends on an already running application server's instance. 
As per error log message, it looks like Payara server is not running so requires you to start up a Payara server outside of the build.
> Could not connect to DAS on: http://localhost:4848 | Connection refused: connect
