### ISSUE TITLE
Missing NetBeans plugins

### ISSUE THREAD

**Issue by stevyrino** [jeddict/jeddict#316]
Using latest version of JEDDICT 5.2 plugins:

Product Version: Apache NetBeans IDE 10.0 (Build incubator-netbeans-release-380-on-20181217)
Java: 1.8.0_192; Java HotSpot(TM) 64-Bit Server VM 25.192-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_192-b12
System: Linux version 4.15.0-46-generic running on amd64; UTF-8; en_CA (nb)
User directory: /home/stevyn/.netbeans/10.0
Cache directory: /home/stevyn/.cache/netbeans/10.0

see attached pic.

![Screenshot_2019-03-13_11-37-22](https://user-images.githubusercontent.com/16284559/54306201-16aecf00-4586-11e9-9ce6-d761e9963b8a.png)

**Comment by jGauravGupta** [comment]
As [download page](https://jeddict.github.io/page.html?l=p/download) list binaries, hope you are trying to install Jeddict v5.2 binary compatible with NetBeans IDE 10.0 : http://plugins.netbeans.org/download/plugin/9878
You may also checkout full bundle : https://github.com/jeddict/jeddict/releases/download/5.2/Jeddict_5.2_with_Apache_NetBeans_IDE_10.0.zip

**Comment by stevyrino** [comment]
Hello:
Your first link gives me "Not Found" when selecting top item in select box.  Your third link in message also gives "Not Found" message.

This message is intended only for the use of the individual or entity to which it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you are not the intended reader, then you must destroy this communication immediately. 

    On Wednesday, March 13, 2019, 9:14:21 p.m. PDT, Gaurav Gupta <notifications@github.com> wrote:  
 
 
As download page list binaries, hope you are trying to install Jeddict v5.2 binary compatible with NetBeans IDE 10.0 : http://plugins.netbeans.org/download/plugin/9878
You may also checkout full bundle : https://github.com/jeddict/jeddict/releases/download/5.2/Jeddict_5.2_with_Apache_NetBeans_IDE_10.0.zip

**Comment by jGauravGupta** [comment]
Thanks for reporting, I have updated those broken links.

**Comment by slavb18** [comment]
There is also problem with netbeans 11
![nb2](https://user-images.githubusercontent.com/2534896/58743086-32669a80-843c-11e9-8dd6-e4b81759c559.png)
![nb](https://user-images.githubusercontent.com/2534896/58743091-398da880-843c-11e9-9fa8-92777eab4c07.png)

**Comment by slavb18** [comment]
Netbeans 11.1 is out. Could you please add support for NB 11.X ?

**Comment by jGauravGupta** [comment]
NetBeans 11.1 maven artifacts release is still due https://mvnrepository.com/artifact/org.netbeans.api/org-openide-util. Once it will be available, a new version of Jeddict will be release with NetBeans v11.1 support.

**Comment by jGauravGupta** [comment]
Closing ticket as Jeddict 5.3 released with Apache NetBeans 11.1 support: https://github.com/jeddict/jeddict/releases/tag/5.3
