### ISSUE TITLE
Visualize DB the model with enumerated field, referencing enum out of the domain package

### ISSUE THREAD

**Issue by ReneKuzica** [jeddict/jeddict#361]
##### **Overview of the issue**
Visualize DB from model, where enumerated field is referencing data type out of the domain package. Generating is working well.

##### **Expected Outcome**
Visualized DB tables in Jeddict window.

##### **Current Outcome**
Error dialog: Class Not Found in classpath
"my.project.enums.MyEnum" class is not available in the projects class path, please add the dependency.

##### **Steps to Reproduce**(Only for bug reports) 
1) Create my.project.enums.MyEnum in your empty project
package my.project.enums;
public enum MyEnum {
   ONE, TWO;
}

2) Store this model, open in Jeddict editor and right click to "Visualize DB"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" ptype="MONOLITH" ppkg="my" epkg="project.entities" v="5.2" rws="_157417470414670" Pws="_157417470414670" cws="_157417470414670" persistenceUnitName="DEFAULT_PU" sm="false" xs="false" id="_157417470414569" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity compositePrimaryKeyClass="MyClassPK" abs="false" class="MyClass" v="true" jbn="false" xre="false" m="false" rootElement="_157417470414569" id="_157417471049271">
        <jpa:ath>z0002wjj</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="my.project.enums.MyEnum" v="true" xvt="" name="attribute" id="_157417471707174">
                <jpa:xwm/>
                <jpa:xm/>
            </jpa:basic>
            <jpa:id attribute-type="Long" v="true" xvt="" name="id" id="_157417471049872">
                <jpa:xwm/>
                <jpa:xm/>
                <jpa:generated-value strategy="DEFAULT"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="MyClass.findAll">
            <jpa:query>Select e from MyClass e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="MyClass.findByAttribute">
            <jpa:query>Select m from MyClass m where m.attribute=:attribute</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:wsl>
        <jpa:ws n="Main" id="_157417470414670">
            <i ref="_157417471049271" x="252" y="116"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>

##### **Jeddict Version(s)**

NetBeans 8.2
Jeddict 5.2

**Comment by jGauravGupta** [comment]
Hi @ReneKuzica,

I can't reproduce the issue by adding enum attribute to entity which is not in classpath and db diagram shown without any issue. Please share the exception stacktrace.

**Comment by ReneKuzica** [comment]
[JeddictError.zip](https://github.com/jeddict/jeddict/files/3936134/JeddictError.zip)

Hi Gaurav, please open attached maven project. There are two JPA files. The 1st will not visualize the DB (error message I've reported), the 2nd is ok. The difference is in use of @Enumerated. Thanks for investigation.

**Comment by jGauravGupta** [comment]
Thanks @ReneKuzica for the quick response, I can reproduce the issue with basic (non-enum) attribute with a type not available on the classpath.
