### ISSUE TITLE
@Enumerated(EnumType.STRING) is generated as @Enumerated("EnumType.STRING")

### ISSUE THREAD

**Issue by skonx** [jeddict/jeddict#363]
Hi.

Enumerated annotations are translated with a String.
Same behaviour with other annotations (like @Inheritancec annotation for example).

##### **Jeddict Version(s)**

5.3 on Netbeans 11.1

**Comment by skonx** [comment]
workaround : add the annotation on the field/property and add required imports in the snippets

**Comment by jGauravGupta** [comment]
Duplicate of https://github.com/jeddict/jeddict/issues/339
