### ISSUE TITLE
Imports missing in generated source code when Remove Unused Imports option enabled

### ISSUE THREAD

**Issue by juliensie** [jeddict/jeddict#370]
##### **Overview of the issue**

Jeddict 5.4 doesn't anymore declare `import` declarations generating source code.

##### **Expected Outcome**

`import javax.persistence.Id` should be added during the export.

##### **Current Outcome**

No class/method import.
IDE can be used to fix imports.

##### **Steps to Reproduce**(Only for bug reports) 

https://github.com/trendev/jeddict-issue.git

##### **Jeddict Version(s)**

5.4 on NB 11.2 / oracle jdk-8u221-macosx-x64

**Comment by skonx** [comment]
<img width="889" alt="netbeans_settings" src="https://user-images.githubusercontent.com/19473981/70838538-15f2e400-1e09-11ea-9ca4-c329bac1238c.png">

Uncheck the option `Remove Unused Imports` and `Organize Imports` fixes the issue.

Should be closed or improved 😎

**Comment by jGauravGupta** [comment]
Hi @skonx,

I can't reproduce the issue, May you try to clean the system cache or use the new setup: https://github.com/jeddict/jeddict/releases/download/5.4/Jeddict_5.4_with_NetBeans_IDE_11.2.zip

Also, that's a very basic feature without it, [Travis build](https://travis-ci.org/jeddict/jeddict) shouldn't have been passed.

**Comment by skonx** [comment]
Hi @jGauravGupta, those 2 options doesn't work well using jeddict source code generator.
I've tested on a from-scratched Netbean 11.2 & jeddict 5.4 config without any settings expect those one.
I guess the issue should be closed.
Thanks for your quick reply.

NB: if you can point the package in your code, I'll have a look.

**Comment by jGauravGupta** [comment]
Hi @skonx,

Apologies I overlooked it, now I can reproduce the issue after enabling the "Remove Unused Imports" option. Jeddict source generation and IDE auto inspection are not in sync although not a blocker issue.

Thanks for reporting it.

**Comment by jGauravGupta** [comment]
Here(https://github.com/jeddict/jeddict/blob/master/orm-generator/src/main/java/io/github/jeddict/orm/generator/util/ORMConverterUtil.java#L222) source snippet generated from `freemarker` templates copied to file.
