### ISSUE TITLE
cannot open jpa file in netbeans

### ISSUE THREAD

**Issue by charlielai0725hk** [jeddict/jeddict#386]
##### **Overview of the issue**

cannot open jpa file to edit in netbeans 11.2

##### **Expected Outcome**

open the jpa file edit page

##### **Current Outcome**

netbeans popups submit bug report windows

##### **Steps to Reproduce**(Only for bug reports) 

environment:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
host: ubuntu 18.04

create a new jpa file in any package, and double click the jpa file, netbeans error popup show

##### **Jeddict Version(s)**

5.4.1

**Comment by jGauravGupta** [comment]
Please share the Apache NetBeans version and attach the modeler file.

**Comment by charlielai0725hk** [comment]
all the installation files downloaded from https://github.com/jeddict/uc/releases/download/11.2/updates.xml by setting up the update center

but if the files help to resolve the problem, may i ask the files location is under {netbeansDir}/jeddict? those files are mainly jar and xml?

**Comment by jGauravGupta** [comment]
Please share the JPA modeler file, not the binary file. Also, share the error message and stack-trace.

**Comment by charlielai0725hk** [comment]
Sorry that i discover the problem now, there is a conflict with another plugin called NBANDROID.
Jeddict runs fine now, Thanks for following up.
