### ISSUE TITLE
Reverse engineering jeddict enitity class has no primary key specified

### ISSUE THREAD

**Issue by broproo** [jeddict/jeddict#391]
##### **Overview of the issue**

what should i do

##### **Expected Outcome**

shoing database diagram

##### **Current Outcome**

bug
##### **Jeddict Version(s)**

[1539549905_Jeddict_5.2_for_NetBeans_IDE_8.2](url
[ApplicationFile.zip](https://github.com/jeddict/jeddict/files/4274217/ApplicationFile.zip)

)

**Comment by jGauravGupta** [comment]
Please add the sufficient information and step to reproduce.

**Comment by jGauravGupta** [comment]
Test with the attached modeler, can't reproduce the issue, please reopen the ticket with the sufficient details.
