### ISSUE TITLE
JPA Static Metamodel generates invalid sources

### ISSUE THREAD

**Issue by ReneKuzica** [jeddict/jeddict#434]
##### **Overview of the issue**
Metamodel generation failed

##### **Expected Outcome**
<pre>
package my.test.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

/**
 * @author z0002wjj
 */
@StaticMetamodel(Test.class)
public class Test_ {

    public static volatile SingularAttribute<Test, Long> id;

    public static volatile SingularAttribute<Test, String> attribute;

}
</pre>

##### **Current Outcome**
<pre>
package my.test.domain;

import javax.persistence.metamodel.StaticMetamodel;
Java method "io.github.jeddict.orm.generator.compiler.def.ClassDefSnippet.getImportSnippets()" threw an exception when invoked on io.github.jeddict.orm.generator.service.staticmetamodel.StaticMetamodelClassDefSnippet object "io.github.jeddict.orm.generator.service.staticmetamodel.StaticMetamodelClassDefSnippet@647bb035"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #foreach importStatement in classDef...  [in template "unknown" at line 7, column

1]
----/**
 *
 * @author The following has evaluated to null or missing:
==> author  [in template "unknown" at line 12, column 14]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${author}  [in template "unknown" at line 12, column 12]
----
 */
@StaticMetamodel(Test.class)
public class Test_ {

    public static volatile SingularAttribute<Test, Long> id;

    public static volatile SingularAttribute<Test, String> attribute;

}
</pre>

##### **Steps to Reproduce**(Only for bug reports) 
I used OpenJDK15, NetBeans12.1, Jedict 5.4.3
The simplest JPA diagram with one entity (id, attribute).
Source with Entity was generated correctly, even I had to switch off Remove unused imports and Organize imports in NB options.

##### **Jeddict Version(s)**
Jeddict 5.4.3

**Comment by jGauravGupta** [comment]
Please attach the modeler file to reproduce the issue.

**Comment by ReneKuzica** [comment]
[Test.zip](https://github.com/jeddict/jeddict/files/5923809/Test.zip)

**Comment by ReneKuzica** [comment]
The same issue with the latest NetBeans 20 + Jeddict 6.2.0
