### ISSUE TITLE
NetBeans 12.2 Plugin Installation fails

### ISSUE THREAD

**Issue by rrohm** [jeddict/jeddict#444]
##### Installation of Jeddict 5.4.3 fails with NetBeans 12.2

If I download Jeddict v5.4.3 for Netbeans 12.1, unzip it and select all the .nbm files for plugin installation in NetBeans 12.2, it fails with messages like: 

Some plugins require plugin io.github.jeddict.modeler.lib to be installed.
The plugin io.github.jeddict.modeler.lib is requested in version 5.4.3.  
The following plugin is affected:       
Installer 

It is always the same, there seems to be no workaround if I try to load one and install, load all and select all for installtion, load all and install only one etc.
It seems the .nbm files are not recognized. 

##### **Expected Outcome**
I would either expect the installation in NetBeans 12.2 to succeed, 
or to be shown an appropriate notice that Jeddict v5.4.3 for NetBeans 12.1 is not compatible with NetBeans 12.2.

##### **Current Outcome**

The NetBeans 12.2 plugin installer does not recognize the nbm files properly. It always shows messages like: 
Some plugins require plugin io.github.jeddict.modeler.lib to be installed.
The plugin io.github.jeddict.modeler.lib is requested in version 5.4.3.  
The following plugin is affected:       
Installer 

You cannot proceed or work around, you can only cancel installation.

##### **Steps to Reproduce**(Only for bug reports) 

- donwload Jeddict_5.4.3_for_NetBeans_IDE_12.1.zip
- unzip it
- start NetBeans 12.2
- in the main menu, click "Tools" > "Plugins"
- go to the "Downloaded" tab
- click "Add plugins"
- select all .nbm files from the unzipped package
- OR: try a single one, plus other variations
- Then: click the "install" button with all items selected
- OR: try to install only a single one 
The result is always the same.

##### **Jeddict Version(s)**

Jeddict_5.4.3_for_NetBeans_IDE_12.1

**Comment by jGauravGupta** [comment]
Please install the Jeddict v5.4.4 for NetBeans 12.2 support
https://github.com/jeddict/jeddict/releases/tag/5.4.4

**Comment by rrohm** [comment]
Thank you very much! Now it worked, and ... at a first glace, it really looks and feels great! Thank you for bringing such a tool to NetBeans!
I just tried to understand what I missed the first time, i.e., why I started with the wrong package: I first tried the download page https://jeddict.github.io/page.html?l=p/download - there, v5.4.4 is not listed for download yet.
