### ISSUE TITLE
Apache NetBeans IDE 12.3, installation failed !

### ISSUE THREAD

**Issue by Pingear** [jeddict/jeddict#459]
When I try to install the plugin in Apache NetBeans IDE 12.3 it gives the following errors -

Some plugins require plugin Database Core to be installed.
The plugin Database Core is requested in implementation version 12.1-cade25887c5450e4595fa59e616daee4d2520ee0.  The following plugin is affected:       JPA Modeler 

Some plugins require plugin Maven Embedder to be installed.
The plugin Maven Embedder is requested in implementation version 12.1-cade25887c5450e4595fa59e616daee4d2520ee0.  The following plugin is affected:       jCode Util 

Some plugins require plugin Maven Projects to be installed.
The plugin Maven Projects is requested in implementation version 12.1-cade25887c5450e4595fa59e616daee4d2520ee0.  The following plugin is affected:       jCode Util  Some plugins not installed to avoid potential installation problems.

But I cannot find these plugins at http://plugins.netbeans.org

**Comment by jGauravGupta** [comment]
Released v6.2.0 https://plugins.netbeans.apache.org/catalogue/download/452/jeddict-6.2.0.nbm compatible with Apache NetBeans 20.
