### ISSUE TITLE
Liquibase support

### ISSUE THREAD

**Issue by Namphibian** [jeddict/jeddict#48]
Hi Team.

Before I start I just want to say I really like the plug in a lot. I have been looking for something that I can use to do some serious JPA and DB development. This plugin is certainly looking like it has the right idea and it exposes all the properties I need to fine tune my models. Hopefully my contributions will be helpful in getting momentum from a wider audience so that this plugin can get the attention it deserves.

So while deploying a simple three table example using the Angular and Rest service approach I ran into several SQL related problems on PostgreSQL. The table used to store authorities and users in has some small bugs that are relatively easy to fix.

**1.**  Authority table has a column called "name" this is a reserved word in PostgreSQL and there is a problem with upper and lower case here. When creating a table in PostgreSQL unless you quote the column name it looses all capitalization. 
For Example execute the following on pgSQL:

```
   CREATE TABLE testcaps
    (

        MyName varchar(128)
    )

```

If you look at the table on the server the statement becomes:

```
    CREATE TABLE testcaps
    (   
        myname character varying(128)
    )

```

This can be confirmed by reading this section of [the PostgreSQL manual ](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS). link"

Notice the caps have been replaced by lower case.  If I execute:

```
    CREATE TABLE testcaps
    (

        "MyName" varchar(128)
    )
```

The case is reserved. I suspect you are creating the authority table with a statement like this(I cant find the create table statement the plugin generates so it might be different in your code base).

```
CREATE TABLE authority
    (
        NAME character varying(50) NOT NULL,
        CONSTRAINT authority_pkey PRIMARY KEY (NAME)
    )

```

This changes the casing of the column's name from  **NAME** to  **name** due to PgSQL converting all unquoted column, tables and database names to lowercase and since PgSQL is case sensitive it breaks the sql_insert scripts see example below:

```
INSERT INTO AUTHORITY ("NAME") VALUES ('ROLE_ADMIN') 
```

If I change this to:

```
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN') 
```

This works even though the column case does not match as PGSQL will convert the column name since it is not quoted.

**Suggestion:**
1. Quote all column names in the create and insert statements.
2. Remove the quotes on all statements so that it always refer to lower case however if you decide on this route you are going to have problems with the reserved word name. Thus if you remove quotes in the statements around column names you will probably have to rename the column to authority_name to avoid using reserved word. 

According to [best practice on PgSQL](http://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive) it probably best to use lowercase names all over. 

The second one is that on the insert statement you are inserting a boolean value for ACTIVATED column. The script is below: 

`INSERT INTO ACCOUNT(ID, LOGIN, EMAIL, FIRST_NAME, LAST_NAME, LANG_KEY, ACTIVATED, CREATED_DATE, PASSWORD_HASH) VALUES (1002, 'admin', 'admin@example.com', 'Admin_F', 'Admin_L', 'en', 1, '2016-08-10 09:27:58.256', '21232f297a57a5a743894a0e4a801fc3')`

However you specify 1 which is then implicitly cast as an _integer not a boolean value_. Change the 1 in the insert list to `1::boolean` and the error goes away.

Thus the following works:

`INSERT INTO ACCOUNT(ID, LOGIN, EMAIL, FIRST_NAME, LAST_NAME, LANG_KEY, ACTIVATED, CREATED_DATE, PASSWORD_HASH) VALUES (1002, 'admin', 'admin@example.com', 'Admin_F', 'Admin_L', 'en', 1::boolean, '2016-08-10 09:27:58.256', '21232f297a57a5a743894a0e4a801fc3')`

One last thing in relation to PostgreSQL when I explicitly set a id property of a entity class  to use an identity generator to table it does not change the data type appropriately in the create table statement.
PgSQL does not have auto-increment datatype as in MySQL or an identity data type like MS SQL server. PgSQL uses **serial** for **auto-increment integers** and **bigserial** for **auto-increment big int** data types.

Thus for this functionality to be satisfied you need to change the create table statement for pg tables with table id generation strategy from:

```
CREATE TABLE numtest
(
    numberid BIGINT NOT NULL
)


CREATE TABLE numtest
( 
    numberid BIGSERIAL NOT NULL
)
```

Doing this will create a proper auto-number column and also create the appropriate sequence generator on PgSQL. 

I included the XML for JPA design view below. Hope it makes sense. Have fun.

```

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.namphibian.jpamodellerdemo" v="2.5" thm="PDarkColorScheme" dbthm="PDarkColorScheme" sm="false" xs="true" id="_14729010538682" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity name="Person" lbl-ref="_14729012845345" xre="false" compositePrimaryKeyClass="PersonPK" abs="false" class="Person" visibile="true" minimized="false" rootElement="_14729010538682" id="_1472901084795">
        <jpa:ts e="true">
            <jpa:a>_14729010848363</jpa:a>
            <jpa:a>_14729012845345</jpa:a>
            <jpa:a>_14729012895736</jpa:a>
        </jpa:ts>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="Name" id="_14729012845345">
                <jpa:bv>
                    <jpa:nn/>
                </jpa:bv>
                <jpa:column name="FistName" unique="false" nullable="true" insertable="true" updatable="true" length="128" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="Surname" id="_14729012895736">
                <jpa:bv>
                    <jpa:nn/>
                </jpa:bv>
                <jpa:column name="LastName" unique="false" nullable="true" insertable="true" updatable="true" length="128" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1472901345350" visibile="true" name="personProductOrders" id="_147290148440612">
                <jpa:join-table name="Orders">
                    <jpa:join-column name="PERSONID" rc="PERSONID" unique="false" nullable="true" insertable="true" updatable="true" column-definition="" table="Orders"/>
                </jpa:join-table>
                <jpa:join-column name="PERSONID" unique="false" nullable="false" insertable="true" updatable="true"/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" ui="false" id="_14729010848363">
                <jpa:bv>
                    <jpa:nn/>
                </jpa:bv>
                <jpa:column name="PersonID" unique="true" nullable="false" insertable="true" updatable="false" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Person.findAll">
            <jpa:query>Select e from Person e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Person.findByName">
            <jpa:query>Select p from Person p where p.Name=:Name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Person.findBySurname">
            <jpa:query>Select p from Person p where p.Surname=:Surname</jpa:query>
        </jpa:nq>
        <jpa:table name="Person"/>
    </jpa:entity>
    <jpa:entity name="Orders" lbl-ref="_14729013453517" xre="false" compositePrimaryKeyClass="PersonProductOrderPK" abs="false" class="PersonProductOrder" visibile="true" minimized="false" rootElement="_14729010538682" id="_1472901345350">
        <jpa:ts e="true">
            <jpa:a>_14729013453517</jpa:a>
            <jpa:a>_147290152346514</jpa:a>
        </jpa:ts>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="Amount" id="_147290152346514">
                <jpa:bv/>
                <jpa:column name="Amount" unique="false" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14729013453517">
                <jpa:bv>
                    <jpa:nn/>
                </jpa:bv>
                <jpa:column name="OrderID" unique="true" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="PersonProductOrder.findAll">
            <jpa:query>Select e from PersonProductOrder e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="PersonProductOrder.findByAmount">
            <jpa:query>Select p from PersonProductOrder p where p.Amount=:Amount</jpa:query>
        </jpa:nq>
        <jpa:table name="Orders"/>
    </jpa:entity>
    <jpa:entity name="Product" lbl-ref="_147290135864911" xre="false" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" visibile="true" minimized="false" rootElement="_14729010538682" id="_1472901348563">
        <jpa:ts e="true">
            <jpa:a>_14729013485659</jpa:a>
            <jpa:a>_147290135864911</jpa:a>
        </jpa:ts>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="Description" id="_147290135864911">
                <jpa:bv>
                    <jpa:nn/>
                </jpa:bv>
                <jpa:column name="Description" unique="false" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1472901345350" visibile="true" name="personProductOrders" id="_147290150050813">
                <jpa:join-table name="Orders">
                    <jpa:join-column name="PRODUCTID" rc="PRODUCTID" unique="false" nullable="true" insertable="true" updatable="true" column-definition="" table="Orders"/>
                </jpa:join-table>
                <jpa:join-column name="PRODUCTID" unique="false" nullable="false" insertable="true" updatable="true"/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" ui="false" id="_14729013485659">
                <jpa:bv>
                    <jpa:nn/>
                </jpa:bv>
                <jpa:column name="ProductID" unique="true" nullable="false" insertable="true" updatable="false" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByDescription">
            <jpa:query>Select p from Product p where p.Description=:Description</jpa:query>
        </jpa:nq>
        <jpa:table name="Product"/>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
        <db u="jdbc:postgresql://localhost:5432/jpdemo" n="postgres" p="123" d="org.postgresql.Driver"/>
    </jpa:c>
    <jpa:diagram>
        <plane elementRef="_14729010538682">
            <shape elementRef="_1472901084795">
                <Bounds x="320.0" y="127.0" width="176.0" height="147.0"/>
            </shape>
            <shape elementRef="_1472901345350">
                <Bounds x="618.0" y="154.0" width="211.0" height="92.0"/>
            </shape>
            <shape elementRef="_1472901348563">
                <Bounds x="829.0" y="307.0" width="176.0" height="126.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>


```

**Comment by jShiwaniGupta** [comment]
Thanks for the detailed explanation,.

In this case, Table generation is done by JPA provider so @Column need to modifed at name attribute
https://github.com/jGauravGupta/jCode/blob/master/RESTGenerator/src/org/netbeans/jcode/template/entity/Authority.java.ftl

And for Insert operation, we have added **insert.sql** with persistence.xml property :
```xml <property name="javax.persistence.sql-load-script-source" value="META-INF/sql/insert.sql"/> ```

**insert.sql** is available in the following path for **config-resource.zip/insert.sql**
https://github.com/jGauravGupta/jCode/tree/master/RESTGenerator/src/org/netbeans/jcode/template/config



Currently, for stable release, we will incorporate it but at the end we have to migrate to **LiquiBase**.

**Comment by jGauravGupta** [comment]
Hi @Namphibian , 
Welcome and thanks for your interest in JPA Modeler. 

It have 3 main component : 
1- **JPA Modeler** 
 Knowledge required : [NBModeler](https://github.com/jGauravGupta/NBModeler), NetBeans Visual API etc.
2- **DB Modeler** 
 Knowledge required : Eclipselink, [NBModeler](https://github.com/jGauravGupta/NBModeler), NetBeans Visual API etc
3- **JavaEE Generator** - [jCode](https://github.com/jGauravGupta/jCode)
 Knowledge required :  Template engines (Freemarker, EJS etc)

New features for development :  

1- **DB Modeler** - Secondary Table support, Issue fix
2- **JavaEE app Generator** - Elastic search, Liquibase, Hazelcast, Angular2, Gradle, JSON spec, jCache spec etc

You may select the feature from the above list or suggest us if u are looking for another good feature atm.

Thanks again for your support :)

**Comment by Namphibian** [comment]
Namaste Mr Gupta.

Thanks for information around the projects and layouts. I cloned the source
last night and had a brief look at the various pieces. I was suprised at
how many packages there were in the JPA modeller. Just to clarify from the
20 minutes I spend looking at the code you are using EclipseLink to
generate the tables? I got to the table generator class file but got
interupted by my 2yr old looking for a lullaby (not that I sing well) so
could not tie the pieces together.

It would make sense to let JPA handle table creation as it will handle the
different SQL dialect quiet comfortably. Most of my development efforts at
the moment are JSF based MVC using PrimeFaces. I have some new developments
that are heading to be purely REST, Angular based.

I have not been able to look at the code the JPA modeller generates due to
household time constraint. Thus I am not sure how the current plug in
handles loading large lists. This is one flaw in the current JSF from
Entity classes wizard in Netbeans, once a table reaches a couple of
thousand rows there is severe impact on performance ans resource usage.  I
have managed to create a generic library to handle large lists on web pages
letting JPA and EJB handle the paging. This is done with
CriteriaQueryBuilder in JPA if I remember the clasd name correctly. This
works very well on JSF pages and allows the use of generic sorting and
filtering on lists of millions of records.

This feature would be a must serious development work as big data is not
just in the realm of large organisations anymore.

I will review the code a little more and then come up with some solid
suggestions.

Kind Regards
Neil Franken

**Comment by jGauravGupta** [comment]
Hi @Namphibian ,

**ORM Coverter module :** For Java Class file generation with velocity template
**DB Modeler module :** For table generation on the fly using Eclipselink. 
Yes, some files in this module are not gently written, actually Eclipselink or any other provider has not exposed any API for such case scenario. Because eclipselink is RI and we don't want to write our own ORM like engine to support all database so we decided to use the power of existing ORM that's why the combination of JPA Modeler and DB Modeler gives the full power to developer by selecting different DB.
BTW both Eclipselink(rare issues) and DBModeler have some bug for complex case scenario.

**DB Modeler Logic :** 
JPA model (JAXB) -> Eclipselink Dynamic Entity (Input) -> Eclipselink engine -> Eclipselink DB model definition(Output) -> DB Modeler model and JPA Model -> NBModeler
Both at the input and output time,, eclipselink internal logic is executed by DB Modeler and using the power of ORM engine.
At the input time JPA Modeler entity object is attached with Eclipselink Dynamic Entity and at the output time, it is retrieved from DB Model, so whatever the changes will be done with table by user, it will directly save the model.

**Comment by jShiwaniGupta** [comment]
Currently generated REST & Angular code does not support the pagination, but the next upcoming release after the JavaOne 2016 will have support for both single page pagination(on scroll) and multi page pagination.

**Comment by Namphibian** [comment]
Hi Shiwani.

Thanks I will look into this. I agree using eclipselink is probably the
most neutral way to go.

Good to know about pagination. Once I feel comfortable on how various
pieces of plugin work I will start adding more than just bug reports.

Kind Regards
Neil Franken
