### ISSUE TITLE
Support for Netbeans 14

### ISSUE THREAD

**Issue by buurd** [jeddict/jeddict#521]
##### **Documentation is missing for Netbeans 14**

Trying to test out Jeddict with Netbeans 14 but the documentation seems to be for Netbeans 12. When trying to apply the instructions for Netbeans 12 on version 14 there seems to be several differences that must be adressed. Dependencies is one quite annoing problems where for instance GraalVM.js integration >= 1.6 (release version 1) but only 1.16 with no obivious way to update. 

##### **Expected Outcome**

When following the Quick start guide no unexpected problems occur.

##### **Current Outcome**

Dependecies are missing or are wrong version with no obvios way to update those plugins (are they even possible to update?)

##### **Steps to Reproduce**(Only for bug reports) 

Install Netbeans 14 (current version when writing this)
Add plugin repository: https://github.com/jeddict/uc/releases/download/12.1/updates.xml
Try to follow the https://jeddict.github.io/page.html?l=tutorial/QuickStart. 

##### **Jeddict Version(s)**

v5.4.3

**Comment by jGauravGupta** [comment]
Apache NetBeans 15 support added to Jeddict v6.0 https://github.com/jeddict/jeddict/releases/tag/6.0
