### ISSUE TITLE
Integrate Project Lombok 

### ISSUE THREAD

**Issue by Urbiwanus** [jeddict/jeddict#55]
Hi 

https://projectlombok.org/ offers a nice way to produce , for instance, setters and getters as well as builders and other stuff by adding an annotation 

Example https://projectlombok.org/features/Data.html 

JPAModeler can benefit from this work and keep generated classes ( especially entity classes ) very small

**Comment by jShiwaniGupta** [comment]
Java have already proposal for the same functionality, May be after some year , you will not use lombok :)

But from the current state, lombok generate the boilerplate code at the compile time and the jpa modeler generate the boilerplate code(getter, setter, builder, equals, toString and hashcode etc) before the compile time .

Thanks for your views and happy coding :)
