### ISSUE TITLE
Cannot install jeddict 6.2.0 plugin to netbeans IDE 22

### ISSUE THREAD

**Issue by JamalYounes** [jeddict/jeddict#553]
Error when installing jeddict 6.2.0 plugin to netbeans IDE 22

##### **Expected Outcome**
expect good working with netbeans IDE 22

##### **Current Outcome**

![JeddictErrorInstallation](https://github.com/jeddict/jeddict/assets/24374921/6727f5e3-b7c8-4659-9dc0-aeed41930621)

##### **Jeddict Version(s)**
6.2.0

**Comment by jGauravGupta** [comment]
v6.4.0 released for Apache NetBeans 23 : https://plugins.netbeans.apache.org/catalogue/?id=82
