### ISSUE TITLE
Jeddict AI Assistant Contribute

### ISSUE THREAD

**Issue by TFyre** [jeddict/jeddict#555]
##### **Overview of the issue**

Jeddict AI Assistant Source Code

##### **Expected Outcome**

Contribute to source code to enable other langchain4j modules.

How can I contribute to this project? I tried to find the source 😄

**Comment by jShiwaniGupta** [comment]
Hi,

Thank you for your initiative to contribute; I truly appreciate it! Currently, the repository is private, but it will be made public in the near future.

The next release will support various models, including Mistral, Google, Ollama, and more.

Which model are you particularly interested in?

![image](https://github.com/user-attachments/assets/26b123b6-9ed9-4fce-93e0-edad1ace2888)

**Comment by TFyre** [comment]
I want to integrate it with sourcegraph's cody... which uses the openai models, but with a different base url

im guessing it would primarily be config options without having to change too much in the current plugin

**Comment by jShiwaniGupta** [comment]
Hi, 
**Jeddict AI Assistant v1.8 is released:**  
[https://plugins.netbeans.apache.org/catalogue/?id=103](https://plugins.netbeans.apache.org/catalogue/?id=103)

For the above requirement, please go to:

1. **Tools > Options > Jeddict AI Assistant**
2. **Providers Tab > Provider > Select `CUSTOM_OPEN_AI`**

![image](https://github.com/user-attachments/assets/05518003-92b7-4b80-af44-8ec1bbb0b6a6)
