### ISSUE TITLE
Slowness issue

### ISSUE THREAD

**Issue by jGauravGupta** [jeddict/jeddict#60]
JPA modeler with more than 100 entities have slowness in drawing and visualizing the connection.

**Comment by jGauravGupta** [comment]
OrthogonalSearchRouter.routeConnection(ConnectionWidget widget)  -> search(region) is the main root cause for slowness.
Workaround : max depth will vary based on number connection witdget.

**Comment by vaganovdv** [comment]
Thanks a lot for your answer!
Great project!


>Среда, 21 июня 2017, 11:03 +10:00 от Gaurav Gupta <notifications@github.com>:
>
>OrthogonalSearchRouter.routeConnection(ConnectionWidget widget)  -> search(region) is the main root cause for slowness.
>Workaround : max depth will vary based on number connection witdget.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Ваганов Дмитрий Валерьевич
Сот. +79147719993
