### ISSUE TITLE
Renaming meaningful?

### ISSUE THREAD

**Issue by Chris2011** [jeddict/jeddict#92]
In case that this tool gets more and more complex with a lot of other features than to create JPA models, etc. would it be meaningful to rename the project? I think with the ORM converter and the DB modeler and DB tools (Future release ;) it gets much more functionality what has nothing todo with JPAs. Only a suggestion :)

**Comment by jGauravGupta** [comment]
Currently we have three Module Suite : 

1. JPA Modeler  (related to JPA Modeling & JPA code generation)
2. JCode (JavaEE code generation)
3. NBModeler (NetBeans Modeling)

But the DB tools(Services>Databases) have nothing to do with JPA means it will be only DBA oriented tool and will not use any functionality(api) of **JPA Modeler **and** jCode**.

So, it should be separate module(plugin) and only implementation of **NBModeler**. But yes , we could package it with JPA Modeler for installation.

**Comment by jGauravGupta** [comment]
JPA Modeler started with only simple modeling of entities, jpa code generation and the last one reverse engineering. The name of each sub-module of JPA Modeler is good according to the their task.

But now JPA Modeler (packaged with jCode) has covered the complete JavaEE application scope and many other functionality that is required by Java EE developer and full stack developer.
And the JPA Modeler name does not represent the complete software. So I am also interested in renaming the distribution/site name not the JPAModeler, jCode etc. I will proceed for this in future(may be after 1 year) with twitter polls etc. You can also suggest your view on re-naming or discuss on slack.

**Comment by Chris2011** [comment]
ok sure. thx

**Comment by jGauravGupta** [comment]
Hi @Chris2011 ,
The JPA Modeler has been renamed to Jeddict https://jeddict.github.io .
